%!PS-Adobe-3.0 EPSF-3.0
%%Creator: Adobe Photoshop Version 13.0.1 20120808.r.519 2012/08/08:21:00:00
%%Title: tlou.eps
%%CreationDate: 21.02.2022 07:25
%%BoundingBox: 0 0 320 176
%%HiResBoundingBox: 0 0 320 176
%%SuppressDotGainCompensation
%ADO_ContainsXMP: MainFirst
%%EndComments
%%BeginProlog
%%EndProlog
%%BeginSetup
%%EndSetup
%ImageData: 320 176 8 1 0 320 7 "beginimage"
gsave % EPS gsave
40 dict begin
/_image systemdict /image get def
/_setgray systemdict /setgray get def
/_currentgray systemdict /currentgray get def
/_settransfer systemdict /settransfer get def
/_currenttransfer systemdict /currenttransfer get def
/blank 0 _currenttransfer exec
1 _currenttransfer exec eq def
/negative blank
{0 _currenttransfer exec 0.5 lt}
{0 _currenttransfer exec 1 _currenttransfer exec gt}
ifelse def
/inverted? negative def
/level2 systemdict /languagelevel known
{languagelevel 2 ge} {false} ifelse def
/level3 systemdict /languagelevel known
{languagelevel 3 ge} {false} ifelse def
gsave % Image Header gsave
/rows 176 def
/cols 320 def
320 176 scale
level2 {
/DeviceGray
setcolorspace currentdict /PhotoshopDuotoneColorSpace undef currentdict /PhotoshopDuotoneAltColorSpace undef } if
/picstr1 320 string def
/_rowpadstr 320 string def
/rawreaddata {hasDecodeFile 0 eq {/decodeFile currentfile /ASCII85Decode filter def
                                  /hasDecodeFile 1 def} if
              decodeFile exch readstring pop} def
/padreaddata { _topPad 0 gt       { /_topPad _topPad 1 sub def pop _rowpadstr }
			 { _subImageRows 0 gt { /_subImageRows _subImageRows 1 sub def
									dup _leftPad _picsubstr rawreaddata putinterval }
								  { pop _rowpadstr } ifelse } ifelse } def
/image2 level2 {/image load def} {{begin
Width Height BitsPerComponent ImageMatrix
/DataSource load image end} def} ifelse
/beginimage level2 {{
image2
} def}
{{pop .9 setgray 0 0 moveto 0 1 lineto
1 1 lineto 1 0 lineto fill 0 setgray
0 1 translate 1 cols div 1 rows div scale
/ratio {cols 400 div mul} def
/Helvetica findfont 15 ratio scalefont setfont
5 ratio -20 ratio moveto
(\304\353\377 \350\347\356\341\360\340\346\345\355\350\377 \342 \352\356\344\350\360\356\342\352\345 ASCII85 \355\363\346\345\355 PostScript Level 2) show
/x 128 string def
{currentfile x readline {} {pop exit} ifelse
(~>) search {pop pop pop exit} {pop} ifelse
} loop } def}
ifelse
/hasDecodeFile 0 def
/readdata /rawreaddata load bind def
12 dict begin
/ImageType 1 def
/Width cols def
/Height rows def
/ImageMatrix [cols 0 0 rows neg 0 rows] def
/BitsPerComponent 8 def
/Decode [0 1] def
/DataSource {picstr1 readdata} def
currentdict end
%%BeginBinary:      71498
beginimage
?t!GN@:<SP@UWYP?t*\[B4bahC2%9kAn>LaAnPq!F*2YIE,KH*Bk_="FEMkODeEWn
B4kgg@UW\S@qB4_?smAM?t!JQ@UikU?t!JP@q9%V?smAM@U`bS?smAM?smAM?smAM
?t!JP@:<SQ@U`bT@:EYR?XR8L@U`bT@:<SR@:<SQ?smDN?smAN@:<PP@U`bS?XI2J
?X@,J?X[>N@:<SR?smAN?t!JS@:3MN?XR8L?sd>N?sm>K?smAM?t!MQ?smAM?smAM
?XR8L@:<SQ?sd8K@:<SP?XR8M@:E\R@:<PO?smGP?XR5J?sd8J?XI2L@:3JN?sm>K
?XI2J?<plE?sm>K@UW_S?XR8L?smGS@UNMI?smAM@:<SQ?sm>L@:3PS@q&nV?sd8I
@:EYR@:<SQ?smAN@:EYS@UWYP?t*\ZB4bdhBP;!hAS#C_AS,UkEccGGE,KE)BkV:"
FEVtVEG9'!BP;!i@:<SR@Us%]?smAM?t!JR@q0"W@:<SQA7T+W?sd>N@UW\R?smAM
?smAM?smAM?smAN@:<SQ@U`eT@UW\R?XR8M@UW_T@:<VR@:<VR?smDO?smDO?smAO
@:EYQ?sd8J?XI2K?XR8L@U`_R?XR8M?smDR?smDN?X[;L?smAN?sm>K?smAM?t!MR
?smAM?smAM?smAM@U`eT?sd8J@:<PO?=72L@:N_R@U`_Q@:3MP?XI2J?sd8J?sd;M
@UNSO?sm>J?X@,I?=$uH@:3GL@:EYQ?XR8K?smGQ@UNMI?smDN?t!GN?sd8K?smAM
A7T1Z@:3JN@:<SQ@:EYS?smAN@:E\U@q&kS?t!SWAnGXdAS#FaA7]:]AS#IeDfB`<
E,KE)AnGalEd)qZDeEWnAnGRa@:<VTAS#C_?smAL?t!MT@q9+[@:<PO@preR?XI5M
@:<SQ?smAM?smAM?smAM?XR;M@:<PP@:<VR@UWYP?smAN@UW_T@:<SQ@:<SQ?t!JP
?smDO?sd;L?smAM?XI2J?XR8L?t!GO@:<SQ@:3JN?sd>O?smDM?XR8L@:<PP?smAM
?smAM?t!MQ?smAM?XR8L?sd>N@:<SQ?sd;K?t!JO?XR;N@:EYR@:<MN?smDO?XR8L
?XI2K?sd;N@UWYP?smAL?X@)I?X@)H?sd8J@:<SP?sm>L@:<VS@UNMK?smAM?smAN
?XR5L?smAN@q9%X?smAL@UW\R@:<SQ?smAN@:<YUA7AtS?t*SVAn>LaAS#FaA7]:^
A7T7`Bl.j2Ec5]+An>XiEHQYWDeEWnB4b^c?X[GRAS#C_?smDM?t*VWA7T1[@prbQ
@:<PO?=.,L@UW_S?smAM?smAM?smAM?smAM?t!JO@:<VR@UW\Q?smAN@:E\T@UW_S
?t!JP?t!MQ?t!GN?sd8K?smAM?XI2K?smAM?XR8L@:<PQ@:<PO?smDO?smDN?t!GO
@UW\R?smAM?smAM?t!MR?smAM?smAM?smAN@:EYR?sd8K?smDN?XR;N@:EYQ@:<PO
?smDO?XR8K?sm>K?sd;M@:3JN?sm>J?X@)I?XI,I@:3GL@:3JN?XR8K@:<PQ?smAK
?smAM?sm>K?XI/J@:3MO@q0%Z@:EYR@:<VR@:<SR?smAN@:E_W@prbP?XR;PA7T4^
An>Ob@UrtYA7K+[A8,q"FE284A7T=fE--GRDeEWnB4b[b?t!PUARo=\?t!GN?t*SV
A7T4\@U`_Q@:<PO?XI5M@U`bS?smAM?smAM?smAM?sd;L?smDN?t!GO@:3JN?smAN
@UW_T@:<SQ@:3MP@:<SQ@:<PP?sd8K?XI/J?XI/K?smAM?XR8M@:<SQ@:ESO@:3PQ
?smDN?t!GN@:<SR?smAM?smAM?t!JP?smAM?XR5J?smDO@:EYS@:*DM?smDN?XR;N
@:EYR@UWYP?smDO?smAM?sm>L?sd;M@UNSO?sm>K?X@,I?=.&J@:*AK?sd;K?smAN
?t!GO@:3JM?smDO@:<SP?XI/I?sd;L@q0"Y@:<SQ@:E\T@UW\R?smDO@:<VTA7K"S
?XI5M@q0%\ARo=^@:<VS@:<SSA8,n!FEDD6AS,XjD/siHEbT,tB4b^c?t!MTARo4X
?smAL?t*SUAn5C]@UW\R?t!DM?smAN@UW\R?smAM?smAM?smAM?smAM?smAM?XR8L
@:3JN?smDO@UW_T@UW\R@:<SQ@:<SQ?t!GO?sd8K?sm>L?XI2K?smAL?XR8L@UW\R
@:EVP?smAO@:<SP?t!GN@:<SR?smAM?smAM?t!JP?smDM?sd;K?XR;M@:<SQ?sd;L
?smAM?XR;N@:EYR@:<PO?smDO@:<SQ@:EYR?sd;M@UNSO?XR5J?X@,I?XR5K?sm>K
?sd;K?t!JQ?smAM?smAL@:<SQ@:EYQ?sd8K?smAN@q&kT@q0%[@:<SQ@:<SQ?X[>N
@:<SR@UWYN?XI5LA7T4^An>I^?t!JQ@:<YVAnc(!F*);7AS#OhCN4H=E+iiqAn>L_
?t!JRARo7Y?sm>K?t!MSAn>F\@UW\R?sm>K?XR;N@UW\R?smAM?smAM?smAM@:<SQ
?smAM?smAN?smAM?smAN@UW_T@:<SR?smDO@:<SQ?smAM?XI/J?smAM?smAM?smDO
?XR8L@UWYR@preQ?smAM?smDM?t!JO@:<SR@:<PO?smAM?t!MQ@:<VQ@:3MO?sd;L
@:E\S@:*DM?t!GN?XR;N@:EYR@UWYP?smGP@:<SR@:<SQ?XR5L@:3JN?t!DL?XI2J
?smAM?smAL?smAM?t!MQ?smAM?smAM?t!JP@:<PO@:3GL?XR8M@q/tV@q9+\@:<SQ
@:<SQ?smDO@:3MP@UWYO?XI2K@q0"ZA7K(Y@:<SQ?t!SYBkhC!F)u;;BP;$kC2@s4
C1UsfA7]7[?t!SVAn5C[?smAM@:EYTAn>L^@UW\Q@:<MM?sd>N@UW\Q?smAM?smAM
?smAM?t!JO@:3JO?sd;L?smAM?smDO@U`eT@UW_S?t!JP@:<PP?smAL?X@)J?smAM
?smAN@:3MP?XR8M@:<SRA7B"U?sm>L?t!GN?t!GO@UW\S?smAM?smAM?t!MQ@:E\S
@:<SP?XR8L@:<SR?smAM?smAM?XI5M@:EYQ@:EVP?t!JQ@:<SR@:<SQ?sd;N@:3JN
?smAL?XI/I?sd;L@:3JM?smAL@:<SQ@:3MO?t!JP@:E\S?smAM@:3JN?sd;M@q/tV
@U`hW@:EYR@:<SQ@:<SQ@:*AK?XR8L?smDO?XR;M?smDO@:<VS@Us+fDej3-EcZ/8
BP(jkCiOH8C1q-e@UikW@V'(]AS#C]?t!JQ@q0"Y@:<VS@:<SQ?XI5M@UW\R@U`eT
?smAM?smAM?t!GO@U`bR?sm>K?smAM?smAM?XR8M@:<SQ@:E\S@:EYS@UW\Q?t!JP
@:3JN@:<PO?smAN@:3JO?smAM?sd;K?smAM@:<SQ?t!MVAn5@Y@:3JN?smAM?XI2L
?smANA7K1\@UikXC1Lma@:EbXA7AtS?=.,K?XI/J@:<SP@:<ST@q0%Z@UW_R?smAM
?XR8MARf1Y?XI/J?XI2K?<piD?sd8J?sd;M@:<SR?smAM@:<SR?smDO?sm>K?smAN
@:3MPA7AtT@:Wq]?=%#H?t*SS@UW\R?sd;K?XI2K?smDN?smDO?smAN@:<VS@q9:l
E,KN0D/F*&A7T:dCN"0/BP:pc@q/tZA7T7`AS,I`@:<SQ@:<VS@:E\T@:<VS?XI2M
@:<PP@U`eT?smAM?smAM?smDO@UW\Q?smAL?sm>L?smAM?smDO@:<SQ@:E\S@U`bS
@:<SP?t*MO@:3JN@:3JN?smAN?smAM?smAM?t!GN?smAN?smDN?smDQ@q/qT?smAM
?XR8L?=.)J@:3MO@:NeT@q9"YCM[Ki?smDR@preR?sm>L?XI5M@:<VQ?t!JP@:<SQ
@:EYP?smAM?XR8M@q/tV?XI/I?XI2K?!U`C?sm>K?sd8K@:<SQ?XR5J?t!JP?smAM
?smAL?smAM@:3JN@q&hR@:NhY?XR5K@:3SS@:<VR?sd8J?XI2J?smAM?t!JP?smDO
@:<SR@q9=nFE2//AS#F`A7K1cCN"*-B4b[`@:a"^A7]@aAS,Ob@:<VR?t!JP@U`eU
@:E\T?XR;O@:<SQ@:E\T?smAM?smAM?t!GO@U`_Q?t!GO?sd;L?smAM?t!JP@UNVP
@:E\S@:<VS@:EYR?t*PQ@:3JO@:<PP?smDO@:3GM?smAM@:<PO?XI2K?smAM?smDQ
A7AtT?sm>K?XI5M@:EYQ@:<SS?smAN@:E\[IXlEJ?t*PT@q/qU?t*SS?smDO@:E\S
@:*DM@:3MO@UW_S?smAM?XI2LA7K(W?XR8L?XR5K?!UfE?XI/I?XI2K@:<SR?XR8K
?t*PR?sm>L?XR8L?t!JP@:3JN@UNSO@UWbV?smAM@:3JN@:<SQ?sd;K?XI/I?XR5K
@:3MP@:<SQ@U`eT@:X+nF`M5.@q&nW@U`n`Ci=0,B4PO^@V'+^A7fFeBOtac@U`eT
@:<MN@U`eU@U`bS?XI2L@U`bS@UW\R@:<PO?smAM?t!JP@U`bR?smDO?smAM?smAM
?XR;N@:<PP@U`eT@:EYR@U`bS?t!JQ@:3MP@UW\R?smAM@:3JN?smAN@:<SP?XR8L
?sm>L?X[DRA7K%T?sm>L?sd;LBPM@#DJ<]p@q9+\A7fFcB5iEFARf4\A7B%YA7AtU
@:<PP@:<VS?XR8L@:<SP@UW\S@UW_S?XR8MA78nT?smAL?XI/J?=.#G?sm>K@:3JN
@:<SQ?sm>K?smAN?XI/J?smAM?t!JO@:*DM@:3JN@:<VT@pi_R@:*DM@UW_S?sm>K
?XI2J?smAM?smAN?t!JP@U`bS@:X.nFDtr)@q&kT@:<b_Ci=6/An>I]@:Wt^AS,Od
An>Rc@U`eU@:<PO@q0"Y@UW\R?XR;O@:<SQ@U`eT@:<PO?smAM@:3MP@:<VS@:E\T
?smAM?smAM?XR;N@:<SQ@:<VR@:E\T@:<VR?t!JQ?t!GO@:<SP?smAM?smAM?smAM
@:<PO@U`eT@:3MO@:<SSA7B"U@:<PO?t!MUFF/LdI!0:;B4l!sD/*]rBl%[5CM7Bp
@q0%[A7T4\@prhU@:EYT?smAN?sd;K@UW\R@:<SQ@UNSQ@preR?smDN?sd8J?XI/I
?sd;L@:<SQ@:<SQ@:3JN?XR8L?smAL?sd;K?smAN@:*AL?t!MR@:<SQ@q/qU@:3JN
@:<SP?sd8K?smAM?smAN@:3MP@:E\S@U`bR@:O%iE,B2t@U`bS?t*VZDJsB.B4YU^
@U`n[AS#C`ARo=_@U`eV@UW\RAS,I`@preT?XI2L@UW\R@UW_S@:3JN?sm>L@:<SR
@UW_T@UW_S?smAM?smAM?t!JP@:<SQ@:E\T@UW_T@:EYR?t!JP?smDO@UW\Q@:3JO
@:3JN?smAM?smDPA7K+Y@UW\S@:E\UA7T1X@:3PUB52=+JUr8lDfKW2DeX-=JTP^=
B4bdnBP(pn@qB.]An5F^A7K%V@:EYT?t!GO@:*AK@UW\R@:<SQ@UWbV@prbQ?t!JO
?sd5I?smDN?sd;L@:E\S?t!GN@UW\Q?XR8L?smAL?XI2K?smAN?sd;L@:<YU@q/qU
@q&kT@:3JN@:<SQ@:*AK?smAN@:3JN@:3MP@:<VQA7AtT?t*edChdNk@UW_S?t!SY
Ci=-*B4YO\@:<SS@U`n[AS#=\@q&qW@UikWAnPXa@UW_T?XI2L@:<SQ@U`eT?smAN
?smAM@:<SR@:<VR@UW_T?smAM?smAM?smDO@:<SQ@UW\S@U`bT@:<VQ?t*PQ?t!JP
@:<SP@:3GN@:3JN?smDO@:<VSAnGR`@q9(Y@U`n\B4k^a@V'>!Itio@M0s>ZBl7p6
G%bT.G'@t<@q97^@prn^An>F]AS,I`ARo4X@:<YU@:<SQ@:<MM@UW\R@:NhY@:<YU
@prbQ@:<SP?sd8I?sd;M?sd;K@:EYR?smDN@:EYR?smAM?smAL?sd;L?smAN?smAL
@q0%[A7T1Y@:<SQ@:<SQ@UW_S@:3GL?t*SQ?smGR?smAN?t!JO@preR?t*b`Bk_-g
@:<SP?t!PWC2@X!Bk:a\?t!GP@:E\WA7B"W@U`eUAS,LbAS,F^@UW\R?=.,L@UW\R
@UW\S?smAM?smAM?t!JP@UW_S@:<SR?sm>L?smAM?smAN@:E\S@:E\S@:<VR@:<SQ
?t!JP?t!JP@:<SP@:3JN@:3JN?smDO@:<VTBP;'k@q0"X@V'+`BP(jdCNFfKJrl=\
I;W_2BkV0qAn>I]AR].[@UrnW@:<YUAn5@[A7]@_ARf4Y@:EbY@q/tW@:<MM@:<SQ
@:WkX@:<YV@preR@:3MO?XI/H?sd;M?sm>L@:<SQ?smDN@:<VR?sm>L?sm>K?smAL
?t!JO?sd;KA7K.^B4PL_@:<SQ@UW\R@:3JN?sm>K@UW\S@:E\T@UW\U?smAJ?t!JP
A8#[lAnGXc@preS@:<YZCMdm'A7AtU@:<PN@U`bS@:E\S@UinY@q/tX@UiqY@UW\R
?smDO@:<SR@UW\R@:3GL?XR8L@:<SP@:<SQ@UW\R?smAN@:EYR?smAN@:EYS@:EYR
@:<SR@:<SP?smAL?smDO@:<SP?smDO?sd8JA7]:[@:<\WA8#XkCM.-cChdTrB5).!
J:;ffG'8%ID/=!'C1q3iBkCmdA7T.X@U`eU@U`eU@U`bT@:E\S@Us%\A78hQAn5C[
?t!GN?smDO@UWYP?smAM@:EYQ?XI/I?=.&I?XI/I?sd;L?smAM?t!GN?smDO?XI/I
?XI2K?X[AN@prhS?XR5K?smDN?smAM@:E\S@:<SQ@:3JN?sm>K@U`eT@:<VR@:<VR
@:3JK?t!JRA7]IhAS,L`@UW\R?t!PXBl%Nu@preS@:<SP@:E\T@:E\T@U`hX@q/tX
@UiqX@:EYR?smDN@U`bT@U`bS?sm>K?XR8M@:<SQ@:<SQ@:<SR?smAL?XR8L?smAM
@:<VS@:<SQ?smDP@:<PO?smAM?smAM@:<SP?smDO?sd8JA7T.W@:E_WAS5UfB4bde
BP;!hAnGgtGBInDEH#l9EH#l9D/<lrAnGOaAnGR^@U`bT@UW_T@U`bS@:E\T?t*\Y
ARf1XARo7Z@:*AL?smDO@UWYP?smAM@U`bR?XI/I?X@)I?=.&H?smAM@:3JN?t!JP
?t!GM?sd8J?smAM?t!JO@prbQ?sd8J@:3JO@:<PO@UW_T@UW\R?smAN?t!GN@:E\S
@:<SQ@:<SQ@:3GM?t!JQA7]@eAS#C^@q/qU?t!MTBk_6k@UW\R?t!JN@UW\S@:EYR
@UinY@q/tW@UiqX@:3JN?smAM@U`bT@UW\R?sd8J?XR8M@:<SP@:<SP@:<SR?smAM
?XR8L?smAM?t!JQ@:<SP@:<SR@:<PO?smAM?XR8L?smAL?smDO@UNPM@UW\Q@:E_V
B4YUa@qK@fEHQGEF*W.^EG]Q3E,TN/F)uGDDes-"@qB4^AnYaa@U`eU@U`eU@U`eU
@U`eU?t!VYA7T4\A7T.X?XI/H?smDP@:<SP?XR5K@U`eS?XI/I?X@,J?XI2K@:3JM
@:3JN?smDN?smAM?XI/J?smAL?smAN@:<PO?sd;M@:3MP@U`bR@:E\S@UW\S?smAN
?smAM@:<VS@UW\R@:EYR?smAN@U`eUA7K.\A7K1\@q0"Y?XRASBk_-g@UW\R@:<SP
@:<SR@:<SQ@:<VT@U`bT@q&nU?t!GN?smAN@U`bS@:E\S?sd8J?XR8M@UW\Q@UW\R
@:EYR?smAM?smDN?smAM?smGP@:<SP?smDP@:<PO?smAM?smAM?smAM?smDO@:<PN
?smAN@:Ne[B4YO^@qBFoFa87SI"$HbDJX0+Ci4$*E,ou=Ch[Kk@q0"YA7K+X@U`bT
@U`eT@U`eU@UW\S?t*YXAnGXeA7T+W?XI/I?t!JQ@UWYP?smAM@:EYQ?XR8K?XI2K
?smAN@:<SR@:<SQ?t!JP?sd8J?XI/J?smAL?XR8M@:<PO?XI2K?t!JQ@U`eT@:<VS
@:<SR?XR8K@:E\S@UW\R@:<SQ@:<SP?smANARf4[@UikV@U`kX@q9+\?=.,PBkh6k
@UW\R@:<PN@:3MP@:<SQ@UW\R@UW\S@:E\T@:*DM?smAM@U`bS@UW\R@:*AL?XR8N
@:<SP@:<SQ@:EYS?smAM?smAN?smAM?smDP@UNSO?t!JR@:3JN?smAM?smAM?smAM
@UWYQ@U`bS?=7,K@q&qYBOt[`A7]\/QBRAfN/*"3Df'E.CMms*Ci430CM@?jA7B"X
@q&nU@UW\S@U`bT@UW_T@:<VS@U`eV@qB:bA7K%U?t!JO?smDO@U`_Q@:<PO?t*PP
?XR5J?X@)I?XI2K@:<VR@:EYR?smAM?XI/J?sd8L?sm>K?XR8M?smAL?smDO@:3MQ
@U`eT@U`eT@:EYR?sd8L@UW\S@:<VR@:<VR@:<PO?smDQBOkU_@UW\R@U`hW@q/tX
?XI5QAnP^e@UWYP@:<SO?t!GN@:3MP@:<SQ@UW\R@:<SQ?smAM?smAN@U`bT@UW\R
?smAM?smDO@UW\Q@U`bS@:<SR?smAM?smAN?=$uG?XI/J@:3JN?t!MR@UWYP?sm>L
?smAM?smAM@UW\R@:<SQ?XR;O@UikWB4tslB5E$qV4!6nG]@\>DJjB2Df9K3CMds*
C1_!eA7B"YA7B"W@U`bT@U`eU@U`bT@U`eT@U`eU@:NhZA7T1Y?smAM?smGQ@UWYP
?smAM?t*PQ?sd;L?X@,J?XI2L@UW\R@:EYQ?smAN?XI2K?smDN?XR8K?smDO?sd8K
?XR;N@:3PR@UW\R@UW_S@:EYR?sd;L@:<VS@:<SQ@:EYR@:EVP?t!MUBkV$f@UW\S
@U`hW@q&nV?XI5PAnGXd@UW\R@:3MO?smAM?smAN?t!JP@:<VR@:<SP?smAN?smAN
@:E\T@:<SQ@:3MO?t!JP@:E\R@:<SQ@:<SR?smAM?smAN?=$rF?XR5K?t!JN?smDP
@:3JN?smDN?smAM?smAM@:<VS@:<SQ?smGTARo7ZAS,[lCNkoHZ'L,iFEDVDEGoW/
Ci"$0CM[d#BkM'lBP(ddAS#C^A7K(W@:NbU@UW_T@U`bT@U`bS?t!JR@UinX?smAN
?smDO@UWYP?smAN@:<SQ?sd8K?XI2K?XR8M@:<SQ@U`eT?smAN?sd8K?XR8L?smAM
?XR8L?XI2K?smGS@:<SQ@:<PP@U`bS@:<VR?sd8K@:<YV@UW\R@:<SR@U`_P@:<\X
Bk_6k@:<SPA7K+Z@q&nT?sd>QAnGXd@U`bS?smDM?smAM?smAM@:<SQ@:EYR@:<SQ
@:3MP?smAN@U`bT?t!MQ@:3JN?smDO@UW\Q@U`bS@:<SR?XI,H?XI/J?=$rF?XI/J
@:3JN?smAN@:3GM?t!JP?smAM@:3JO?t!MR@:<SQ@:EeZAn>F\A7ob!GD1p%Jp23V
E,]`6EH>u8EGof4Chma!DK'N8D/3j!BP;$kA7K+Y@UW_T@:EYR@U`eU@U`_Q?smAN
@:E\T@U`eU?XR;O@U`_R?smAN?t*PQ@:*AK?XI/I?XR8M@:<SQ@:E\S?t!GO?XI/I
?smAM?smAM?t!GO?XI/I?X[AR@:3JO?smDN@:EYR@:<SQ@:<VR@:<SQ@:<SR@U`bS
?X@&G?=@ATBkV0lA7T4_A7B"V@:<SP?smDQAS,Od@UW\R?smAM?smAM?smAM?smAN
@:<SQ@:<SQ?smAM?smAN@U`bS@:E\R@:<VS@:<SP@:<SQ@q&kT@:<SQ@:3MP@:3JN
@:3JN?smAM?smAM?smGO@:<VR@:E\S?smAM@:3MO?sd8M@q&eMA7]@cBkV-l?XdV`
H%UTmH@1-gH[0aQE,oo9DJjE0AnPgnC27g5CMINrB4b^cA7K+Z@:E_U@:E\T@U`bT
@q/tV@U`eU?t*VT@q9"W?XdMR?XI2N?=.)J@:<VQ?XI2L?sd8J?smAN@:<VR@UWYP
?t!GN?XR5K?XI/I@UWYO?=75O?XR8K?t!JP?XI2K?smAM@:EYS@:<SQ@:<VR@:<SQ
@:<SQ@UW\R?=$rG?t!PUA7T4\@:<VTARf4Y@:<SP?smGRAS,Lb@:EYR?smAM?smAM
?smAM?smAM?smDO@:<SQ@:3JN?smAN@UW\R@:<SP@:EYR@:<PP?t!JQA78nT@:3MP
@:3MP?sm>L@:3JN?smDO?smAM?XR>O@:<SQ@:<SQ?sm>M@:<PO@:!;M@q&hOAS#Fa
B4tpj@:X"dDfTuEGBnR_H?XCKEH6#9D/='*A7oRlBkqU.C1q6kARf4Z@q&qX@:E\S
@:EYS@U`eU@U`bS@:E\T@:E_VA7T1Y?t!PT?sd;M?=7,K@:<VQ?XI2K?sm>L?XR5K
@:<SR@UNPN@:3MP?sd;K?XI2J@:<PO?smDP?XR5J?XdGP?XI2K?sd;L@UW\R@:<SQ
@:<SR@:<SQ@:<SQ@:<SR?XR8L@:Nk\@q0"X@UW_UARf4Y@:<SO?smDQA7oIb@:<SQ
?smAM?smAM?smAM?smAM?smAM@:<SQ?smAM?smAO@U`bS?t!JO@:<SQ@:3JN@:<SR
A7AtU@:<PP@:3MP?sm>L?smAM?smAN?smAM?X[DP@U`eT@U`_Q?smAM@:EYR?s[2K
AS#:W@q91_B5)$oAnGapG'S=WG^+IYG][nCEH5o5Chdd$A7]IhCMRa%BP(db@UinW
@U`eU@:E\T@U`eT@UW_T@U`eT@U`hW@qK=_@q9(X@:WnY?sd;L?=7/L@UW\Q?XR5L
?sd;K?=.#G?XR8L@:3JN?t!GO?sd;L?XI/J@:<PO?sd>N?XR5J?t!JP?XI2J?XR8K
@:<SQ@:<SQ@UW\R@:<SP@:3JN?smAM?smAO@Uit\@q9+[AS#C^AR]+W@:<SN?smDQ
AS5Ud@:<SQ?smAM?XR8L?smAM?smAM?smAM@:<VR?smAM?XR;O@U`bS@:<PO@:E\T
@:3MO?t!JP@q&kT?t!GP@:<VR?sm>L?t!GN?smAM?smAM?t!MQ@UW\S@:<PP?smAM
@:EYQ?sd8MAnPU\@q9+]BP;$oBl%d4F`_nVH$XgbGB.V@F)c#5CM@NuBP;-tCi!j$
ARf4[@U`hW@:E\U@UW_S@:E\S@U`eT@U`eU@UinWA7fI`@:NeW@q94^?sR/J?XI/K
@:<SO?XR5L?XI/J?XI,I?XI/I?sd;L?smDO?sd;K?XI/J@:3GM?smAN?sd;K?t!JP
?XI/J?sm>K@U`bS@:<SQ?t!JP@:3JM?XR5J?smAN?smAN@:E_V@V'+`B4kjh@prhT
@:3MN?smDQAS>[e@UW\R@:3JN?smAM?smAM?smAM?smAM@:<VR?smAM?smAO@UW\R
@U`bR?t!JP@:3JN?t!JP@q&kT?smDO@:<VR?sm>K?smAM?smDO@:<PN?X[GR@:<SR
@UW\R?XR8L@:EYQ?XI2NBP(g`@:WnYAnGgtI!Km[I"-QkIsuioH?XLSFE)/7CM7Ht
DK'H2E,]Z0@q0"Y@U`hV@q0"Y@UW\R@UW_T@U`eU@U`eU@q0"XAS#@[@:NbWA7oOc
?s[5K?XI/K@:<SP?XR5K?sd;K?XI2J?sd8K?smAM?smDO?XI2J?XI2K?smAO@:3JN
?sd8K?t!JQ?smDN@:<PO@:EYS@UW\R@:3MP?t!GN@:3JN@:<SQ@:3JN?t*SS@:Ee\
C1h0j@preS@:3JL?smDQAS,Oc@UWYQ@:3JN@:3JM?smAN@:<SP?smAM?t!JP?smAM
?smDP@UNVQ@U`eT?t!JQ?smAM@:<SQA7AtT?XR8N@UW_S@:3JN?smAM?smDO@:<PN
?t!PS@U`bS@UW\R?smAM@U`bR?sd>PBPD'f@:<\VAS,^uK6qfiIsufpIXZZmI!^*^
FE;;7C1qBtEH?):EcQ#2B4kjgA7K+Y@q0%Z@U`eV@U`eU@U`eU@q0"YA7T4]AS,Ra
?t!PUA7fFa?sd8K?XI2L@UW\P?XI/K?sd;L?XI/J?XI/I?sd;L?smAM?XR5K?XR8K
?smDO@:<PN?XR8L?t!JP?t!JP@:3JN@UW\R@UW\R@:<SQ?sm>K@:3JN?t!JP?XI,I
?smAM?!q,QAS#=Z@UWYP@:<PN?smDQA7fFb@UW\Q@:<PP?t!GN?smAN@:<SP?sm>L
@:<SQ?smAM?smDO@UNSP@:N_R@:<SQ@:3GM?smDOA7AtT?smDO@UW_T@:3GM?sd;L
?smDO@:<PO?t!PR@U`eT@:<SR?smAM@:<PP?sd>PC2@Tp@:3PSAnGaoIX-6iK7AB"
IXHKhH[0gWF*)>:C2%I!E-#o4E,f`+CM@HpA7K.[@UikW@Uit\B4b^cA7K(YA7T4]
AS,OcAS>jk@:<\W@q91^?smDO?XR8L@UW\P?XI/K?sd8K?smAM?smAM?smAM@:<SQ
?sm>K?smAL?sd>N@:<PO?XR8K?t!MQ?smDN?smAM@U`bT@:<SR?smAM?t!DL@:3JN
@:<SQ?smAL?X[AO>$YKD@UWYN@UW\R@:3JM?smDRA7fCa@:<PP@:<SQ@:3JN?t!JP
?t!JO?sd;L@:<SQ?smAM?smDO@:3MP@:E\S@:<SQ@:3JN?t!JP@q&hR?smDO@:E\T
@:3GM?smAM?smDO@:3JN@:<YS@U`eU@:EYR?smAM@:3JN?sd>QCMRWp?t!JSA7fLi
GBS:^It3*"H[C'`GBItEEcl>;Bk_C!DK'H-D/sH(C1_!e@UrtXA7B(Z@Uj"^C2%Bp
A7T4]ARo=_B4kmkAnPgj@q&qY@q91^@:3MP?=.&I@:<SO?smAN?sd;L?sm>L?smAM
?smAM?smDO?smAM@:3JM?=./M@:ESM?smAL?t!JP?XR8L?sd8J@:<SQ@:EYR@:<PN
?sd8K?XR8L@:NbU@UWYP?smAM@:3MP@:E\T@q/qU@UW\R?!q,RC27X#@:<SQ@:E\T
?XI/I?XI2J@:<SP?smAM@:<VR@:3JN?XI,G?XI2K@pr_M?<puK@:<SQ?t!MPA7K%V
?smAN@:EYR@:3JN@:3JN@:<SR@:<PO@:<PP@U`bS@:EYR?smAM?sd8J?t*_\BP(jf
A7K([BQ83ANJN7@Jq&,nF`r"UHZsLKCM@EpB4Y^jBPV?sCM[j(@UW_UA7fIiBkV3p
C27X'C1q9nA7T4ZA7K.[Ao)@!AnGdl@q'"[A7fFbA78nQ?sm>L?t!DK?smAO@:<SQ
?smAM?smAM?!^iF?smAM@:<SP?sd;L?sm>K?XR5J@UNSN?sd8I?XR8M@:<SQ@UW\R
@:<SR@:<PN?XR5J?X[>N@U`eU@UW\Q?sm>M?t!JP@UW\R@U`bS@UWYQ?=75SC27X"
@:<SQ@U`eU?sm>K?XI/I@:<SQ?smAM@:<VR@:3JN?XI,G?=.)J@pr_N?!UlI?smAN
@:E\SARf.V?smAN@:<SQ@:3JN?smAM@:<SR@:3JN?t!JP@UW_S@:<SQ?smAM@:*DL
?t!Y[B4kggAn5LcBl&0NLk^M6Jpr)pG'A4WGBIhAD/*]sARoIjC2.EqBkqHt@q&nV
@qB:fBkh?sCMR^$AS#LeA7T7\A7T7^B52:!ARoCc@q9.\@qB7a@pi_P?smAL?sm;J
?smAN@:<SQ?smAM?smAM?<plF?smAM@UW\R?smAM?sd8J?XI/J@UNPM?s[2G?XR8M
@:<SQ@UW\R@:<SR@:<PN?sd;L?t!GN@:E\T@UWYP?sm>L?t!JP@U`bT@UW\R@:<MM
?!q)PC27X"@:<SR@U`bT?sd8K?XR5J@:<SQ?smAM@:EYR@:<SP?sd8I?=.)J@pr\L
?=%#J?sd8L?t!JPA7AqS?smDO@:<VR@:3JN@:<PO@:<VS@:<PO@:<SQ@UW\S?t!JP
?smAM?sd8J@:Eh]B4tmgAS>^iDKLGZKRnW'J:2fkG^4RYF`;58CM@HqAnPt#F`heH
CM7?oAn,FaAS>gnC27[)EcQ/;An>ReAnGXcARo@`ASGjmA7B%YA7T7]@Us(`A78nR
@:<PO?smAM?smDO@:<SQ?smAM?smAM?<poG@:3JN@:EYQ?smAM@:3JM?smAM@:3GL
?sd8I?smAO@:<SQ@:<SQ@:<SR@:<PN?sd8K?X[>N@:EYS@:EVP?smAN?smDO@:EYR
@:<SQ@:*AL?!q,QBkqHt@U`bS@U`eT@:<SQ@:<SP@:3MO?smAN@:<SQ@:3JO?XI,G
?XI/J@pr\N?!guJ?=$rH?t!MRA7AtT?smDO@:<SQ?smAM?smAM@:EYS@:<SP@:<PP
@:<SQ?t!JP@:3JN?sd;K@:Eh]B4kggCM@R%FbbHlJUi6!IX?EiH$FRWFDu)7CMINr
Anc1)I=-6[D/*`qD/4!)CM[d#Bl%a0Fa%tKChdTqB4tph@q0%[@q0"X@q0"YA7]:^
AS#CaA78nQ@:<SP?smAM?smDP@UW\R?smAM?sm>L?<poG@:3JN@:EYQ?smAM@:3JN
?smAM?sm>L?sd5H?XR8M@:EYR@:<SQ@:<SQ@UWYP?sd;L?t!GN@U`bT@:<SP?smAM
?XR8M@U`bS@:<SP?XI/J?smDTC27U!@:<SQ@U`eU@:<SR@UW\S@UW\R@:<VR@:EYR
@:3JN?XI,H?=$uG@pr\M?X@,J?XI,I@:<SQA7AqT?XR8M@:<VR@:<PO@:<SQ@:<VS
@:<PO@:<SQ?smAM@:E\S@:3JN?sd;K@:Eh]BP1siC2n99NIuS)JUr?%H?speH$XaZ
F`D>;ChdWsAnPmtFEM\GChdWqE,]l<DJj<.FE`%YI=?TjE,B<%BkqHsA7T4^A7K(X
@UrtYA7K+\AS#=]ARo7W@:<SR?smAM@:3JO@:<VS?smAM?smAL?<poG?t!GN@:EYQ
?sm>L@UNPN?sd;K?smAN?sm>J?smAN@U`bT@:<SQ@UW\S@:<PO?XI/J?X[>M@U`bT
@U`_P?sm>L?smDN@:E\T@:<PO?sm>L?t!MVBkqKs@UW_S@U`eU@:EYR@UW_S@:<VR
@:<VS@U`bS@:<SP?XI/H?=%#I@UWVN?=.)J?XI,I@:<SQA7AqS?smDO@:<SQ@:3MP
?smAN@:EYR?t!GO@:<SQ?smAM?t*SR?smAM?sd;L?t3h^B4tsjDK'`PM1Bo"JUr;u
H?spdI!^-^F`MA:CMRTsAnG[jDJaK;E+s!"CN4K;E,p&GH[^KsJqJW)G'%S7C27U!
ARo=^A7T4\@UikW@q0"XA7]7\A7T1Y@:EYR@:3JN?XR8M@:<SQ?smAM?sm>K?!^lG
?smAM@:<SP?smAM@:3GL?X@,I?sd;L?smAK?sd;M@:<SQ@:<VR@UW\R@:EVO?sd8J
?XR8M@:EYS@:<SP?smAM?smAN@U`eT@:3JM?sm>K?X[JXC27Qr@:<SQ@U`bS@UW\R
@UW_S@:EYR@:<SR@:E\S@:<SP?XI,H?=%#I@UWYP?=.)J?XI2J?sd;LA7AtT?smDO
@:<SR@:<PP?t!JP@UW\R?t!JP@:<SQ@:3JM?t*SR?t!GN?s[2I?t*_\BP1sjEHQGX
IsQ]qJUi,pH@($eH[L-`F`;59CMINrAnPakCi"'2E,B?,D0:&EFEVnYKnkMCN/NRN
I=-0SD/F$%A7T4]A7B"X@q&qX@q0"X@UrtY@qB4]@:<SR@:EVP?XI2L@:<SR?smAM
?smAM?!^lG?t!GN@:<VQ?XR8L?s[2G?=.&H?smAM?smAK?sd;N@:E\S@UW\R@:<SQ
@:EVO?XI/I?XR5L@:EYR@UWYP?smAM?smAN@U`eT@:<MM?XI/I?X[JXBkqHq@:<SR
@U`eU@:<SR@UW\R@UW_T@:<SR@U`bT?t!JO?=.&G?=%#I@:3GL?X@,J?XR8L?sm>K
A7AqS?smDO@:<SQ@:3MO@:<SQ@:<VS?t!JP@:<SP?smAM?t!MR?smAM?sd8J?t*b^
B4kmjEcQS\KnY&-K78,kH@('fH[C*`F`2/7CMIKqAnPajB5;O,D/X<2Fa87UGC"Ub
MMd=NN/NRNL5(2!Df'<+A7]=`ARf1Z@q&qX@UiqZARo7\@qB4^@UW_S@:<SP?smAN
@UW\R?smAM?sd;L?!UcE@:3JN@:<SP?XR5K?XI)E?=$uG?sm>K?smAK?XI2M@:<SQ
@:EYS@UW_S@:<SP?smAM?smAN@:E\T@:3JN?smAM?smAN@:3JM?XI/I?t!JQ?!h&R
C2%<k@UW_S@:<SO@:<SQ@:EYR@U`bT@U`eU@:E\S@:E\R?=@/J?XI5MARSnN?=@5K
?smAL?smDP@q&hQ?sd;K?smDO@:3JP?t!JQ@UW_S@UW_S@:<SR?smAM?t!JP@UNSP
?smDO@:Ek\C27R"G^Y9uI!^<sH#n+TIXQWiEcZ>DFEDJ>Chd]uA7]V"BPML,Ecl_X
K7no1LPUb@QC422R[TS/PEqAeH#@;,@q9+[A7]=_Bk_<tCM@Hp@q0"Y@q94cA7T4]
@q&nU@:<SQ@:EYS?smAM?smAL?!guJ@UWYO?!grH@:3JL?XI/I?XR8K?sd;L?sd8J
@:3MN?t!PS?t*YXARo4W@:EYQ?smAM?smAN@:NbU@:<PO?sm>L?smAM?sd8K?XR5J
?t!JP?!q,SBkq?m@q&kT@:<SP@UNYR@:3MO@UW_T@U`eU@U`bT@:E\R?X@)I?s[8L
Amo"O?XdDM?XR8K?t!GP@UWYP?sd;K?X[AP@:3GO@:<VS@:EYR@UW_S@:EYS?smAM
?t!JP@UWYP?smDO@:<\YBPVO'G^b<uI"-]rEHHJTI<p6fEcZ;DFEDJ>CM@NsAS#b#
BkhU/H@(0mJVAuANK&pWStDXHSXuFEU7@R2KQM$CAnGRbA7]=bBPD3sCM@KqA7fFb
A7K4aA7K+[@:<SQ@:<VS@UW\S?smAM?smAL?!guJ?smAM?!grH?sd5H?XI/I?XI/I
?XI/J?XI/I@U`_Q?smDQ?t!SWARo7X@:EYQ?smAM?smAM@:NbT@:<PO?sd;L?smAM
?sd8K?XI/I@:<VR?"%2TBkh9l@preS@:<PN@UNSQ@:EYR@:<SQ@:<SQ@:EYR@:<SP
?XI2J?=72MARSnO?=I>N@:*AL?smDO@q&hQ?sm>K?X[AO@:<PP?t!JP@:<SQ@U`eT
@:E\T@:3JN@:<SQ@:<PP?t!GO?t*b^BQScPKn+`.IY*'"Fa/7\I=$6cEcQ;EFE2>;
CMITrB5DO(D/XQCJV&K*M3*pbPEV8rUnso_USO]]W2?8\PCdpjC1q9oB4PRdAnYmo
CM7BpB4tskARf7\@q0%Z@:<SQ@:<SQ@UW\R?smAM?smAL?XI2K?smAM?XI2K?sd5F
?XI/I?smAL?XR5K?XR5K@q&kS?sd>M@:E\WAR]+W@U`bR?smAM?smAM@:NbU@:<SQ
?XI/I?smAM@:*AL?XI/J?t*SS?t!V[C2.Bm@U`bS?t!JN?smAM@:<SP@:<SR@:<SR
@:EYR@:EYQ?XI/J@:*DNA78hN?=@;O?sd;K?XR>P@q/qT?sd8J?X[DP@:3JO?smDP
@:<SQ@U`eT@:<SQ@:3GN@:<SQ@UW\R@:<SQ?t3b\F,ZHNT8eehJV&8tGC+deIXHHe
EcQ5CEcQ)8BPM<tCi=B;FF/XrMi3RUQ'R]$QBmo*VP^5fVPU/dX/MecR>u`8CMIQu
BkV-kAS,RgBk_6pCM[]uAn,=]A7T1Y@:E\S?smGP@:<SQ?smAM?sm>K?sd>M?smAL
?=7/K@:!;H?XI/J?XR5J?=.&H?XR5J@q9%V?sd;L@:E\U@U`bS@:<PO?smAM?smAN
@:E\S@:<SQ?XI2K?XR5K@:3GL?XR8L@:<VS@:<b]ChdQm@q&kU@:<PN@:3JN?t!JQ
@:<SQ@:<SQ@:<SQ?t*PP?=@2L?smJPA7/bM?XdJR@UW\O?XmJQ@q&hR?sd8J?XR;N
@:3JN?smDO@:<SQ@U`bT@:<SR?smAN@:<SR@:<VS@q/tW?t3ekPGY1ZX/i(]L4stq
G("pkI=6HfF`__FEH#i5Anc.'DfBoKHA%BCQ'IZ$R@0J2SXu@BUna]\USO]]WMu_g
S<f1eFDYc.ChdWtAnG[hB4kjjD/F*&B4GF^@prhU@:<SQ?sm>N@:<SQ?smAM?XI/J
?XR;M?smAK?XI2J?sd5F?XI,H?XI/J?XI/I?sd8JA7K(V?XI/I@:E\S@U`eT@:<SP
?smAM?smAN@:N_T@:<SP?sm>L?smAM?sd;L?XI/J@:<VR@Uj%dChdNl@preS@:<PM
?t!JO@UNSP@:<SQ@:<SQ@:<VQ?t!JN?XI5N?X[AP@piSK?XdGP@:3GL?=.2O@q&hR
@:*AL?XR;O@:3GN?smDO@:EYR@:EYR@:<SQ@:3JO@:<SQ@:<VSA7T1Z?t=2.OHGHZ
OfcKrO+he#Jq&<#IXZWhGBItHEGfZ2ASlL-E-$8MH\@?AS=#\2S"?4CSY;aMV5C,d
VP^5gWiDnkSt)./IWK@HF)G`,B4tmhAnPdlDJj<,BP(jg@UW\R@:<PO?smAO@:<\V
?smAN?XR5H?t!GN?sm>K?!guH@:*AI?sd8K?XR8L?XI,G?XR5JA7AtU?smAN@:E\S
@:<VS@UW\Q?smAM?smAN@:E\S@:3MP?smAN?smAL?sd8J?XI/J@:EYS@:NnaChdNl
@U`bS@:<PN?sd8L@:3SR@:<SQ@U`bT@U`eT@:<PN?t!GO@UNVT@piSJ?XdGP@:3GL
?XR>PA7K"T?sd8J?XR;O@UNPP?t!JP@:<SQ@UW\Q?t!JQ?t!JO@:E\S@:<SRA7]:]
@Us4qGCY3iKUTicPD4:3NduM-J:2ijG^"7MDf'B0C2e00EHZSKJr,PPSt;F@U8"H[
UnsoaXK/G(XK8P+Y-"h,Vkp,YKn"8hGBS(KB4tmhAS5^mDK'N2CMIHo@U`bS@UNSO
?smAN@UWbW?smAL?XI)E?smAN@:<MK>[:]E?sd8J?XI/J?smAL?!UfE?XI/I@q&hR
?smAO@:E\S@:<YS@:<SP?smAM?smAN@:NbU?t!JO?smAN?smAM?sd8J?XI/I?t*PR
@:NnaCMIHl@UW_S@:<SN@XbTR@:<PP@:<SQ@:<SQ@:<SQ@:<SP?t!HBq-[W?@UNJI
?XdJR@p`VK?XRXDA7AqT?sd8K?XR;P@pi\R@:<SQ@:<SQ@UW\Q?t!JP@:<SQ@:<SQ
@:<SRA7T4\@qB@iBl7m-H]l(OT94knNdc;-Jp_rkH$=@MDJX3-Df9Q8FEMeRMj0[#
T:hmPV5L5iWiE,!ZEUU=ZEga?ZEg^<XK/:sPDt*8FaA@XB4tjgAS>doDK0W6D/3cq
@U`bS@:*DM?smAN@:E_W?smAL?X6rC@:3JN?t!DJ?!LZC?t!MO?sd5J?sd;L?!UfD
?XI/I@:<SP?t!MS@U`bR?t!MQ@:EYR?smAM?t!DN@:NkW@UW_T@:<PO?XR8L?t!JQ
@:*DL?=.,J@:<SR@qB7d@:<PQ@:EW3qshXn?t!PR@:<SQ@:3MQ@UihS?=$rF?XR5]
e6ucpA78kS?t*PR@:<PP@UN[6@UNVP@:<SR?t*\YA7/hQ@UrtX@UNSO?t*SR@pi_R
@:<MO@qK:]@UW\TAS5Rd@q0%[B52=&L9/8$VMg_;IXclrIsZWiEH#c4Bkh<oCi+<E
LPpbATqnTeWiN2$XK8M)X0&J*Z*CU?Za7$G['[-EYct@9V4sE;I<g$YChdZtCMn'-
C2%U+E,K8rAn>I\?t!V[?smAL?t!JP@:3JO?smAL?smAM?smAM?XI2K?smAM?XR8K
?sd;L>[1Q>?=.&I?XR8L?XR>O@:<SR@UW\Q@U`bR?smAM@:3GN@U`eW@UWbT?t3VQ
?smAM?smDN?smAM?=%#I@:<VTBk_0j@UX%]@:<UA?sdAN?t<bV@:<YTA7]Ic@:<ML
?=mVW@UNSTBOY@cC27O!@UNnc@UNSSCgpjg?ug!uC27<qCgpsmEFE["Dfg,3H?EY(
Bm!in@`#cf@UNPcX0&:.@:<VSAS5UdA7K.[AnZ%"N2=Y+Z^%neH[p]rIscZhEH#`2
BkqErD/t5fO,J^IUnsugWiE(uX/`/!WiW;'Yd(O?ZEpmE[C!9GZ*CU?W2-,RKQhT^
Dea!&Ci!s*D/*p+DJNfmAS#F^?t!SX?smAM@:<SQ@:3JO@:3JM?smAM?smAM?XR8L
?smAM?smAM?sd8J?!UcB?!guH?XI2K?t!JQ@:EYS@UWYP@:EYQ?smAM?XdDNchq?m
pL@V&r;ZNS?sr<qp\XSkOo&KnrVp22?sis+o_m-KHM?t0rEs4,o_SC)@G(<_@C,f;
pu0TuojD*5?2_jVs6j=Bpg[e3rqZTl?ss$,A7AsHqdX4;@Ia'boCdLNs']L7qI&jO
qr$CHn`4+dr;U2@s5C`lH!p@CZKV<s@:<VTA7oLc@q0"YAnYssM6".^W2d4]I"?fr
JUM`cEGfT1Ci*j!E.<Y)PDt<[UnjldWMuhqX/i8$X0&M+Yd(L?Za7$G['[3HZE^^?
Xf/%eOb.e#EG]K/D/=$*DeNs(CM.-eAn>O`@:E_X?smAM@:<SQ@UNSP?smAL?smAM
?smAM?XI2K?sm>L?sd;L?sd8K?XR2H?XI/I?XI2K?X[DQ@:EYS@:<PO@UW\R?smAM
?XI2Mci7MSD.7&P?sd=?@UT5\@:K7EQLS@#p\8-(@:Ft!@_MbPXajhfqe:0PIpcge
E+&ZP@.gd5nrdEopg7<3?2\>CNqcu%s'B.3ARVA1@:9'0Md^JrrF9@3@:E[FOC;P7
qdS(<rEir<phOAKn+0u^de.)Jm9sCrf4+_eA=r[+@:<VTARf4Z@:E_VAnPmsLo@#1
WQ1fjIXcitJpMTaDf'?1DJX*)H]<uKQB-fhUSOceWiE%uXK/D'XKAV-Z*L[@Za@'F
['R'DZEgdAY-"UqS<S\RF)Po6Df'?/C27[$AnPX`BPD'i@UiqY?smAM@:EYR@UEMO
@:<PN?smAN?smAM?smAM?smAM?sd;L?sd;L?sd8K?X@)H?XR5K?X[DQ@U`eU@UW\R
@:<SP?smAM@:EVPh#.,3@:?/5@:3L=T4%Vj?t/t?S+U.g@K0bE?smH>q>Fo:A'=lK
r+glY?XdF?l!O=V@JXA>s8)Ne@p`JI>lXctrEipMrF'+.@:>Ju?X`qHpgX)5qI=7>
@:<RBN+-84rFYn@ra9,?qJ]hQrUPF0N;?uZQXO60@q,92S_!gI?X[DRB4GCZ@U`hV
AS,auLn16%[Bl*NI"$[#J9Q6^Des9/Df'T@Mis?mQB79&V5:)iX/i8$Xf\_-Y-+t2
ZEgdAZF$sEZa6sCZa6sEY->%*U7@="F`;59DJj?0CN"0.B4tmfC2@WtAR](V?smDO
@:<SQ@UNSP@:<PN?smAN?smAM?XR8L?smAM?sd8J?XR5J?smAM?sd8J?sm>L?smGP
@U`eU@UW_T@:<SP?smAM?XR>OcM@86?X]B"@:3O8LLBq'@V#LHO8A[3?iOMC@:<PP
@+P9gri]a=rGQBG@:<UEa'b,+IemP_q3PJtpg@H7?Me>AD#.SQra9.6?XJur?sre>
s(;1:r*sF9?t*UFO^V\6q=\B6rEru>s(u4QrU]kqK`,EZemW*F`*d!Nb0]li?X[DT
B4G@X@UWbVAS5k#LR"?nX.c)>I"6j#H?XLQEGKB.E-6YcNg>uqR?+)=VP^8kWiE%u
Xf\_-Xf\_-Z*L^CZa-sFZa6sDZa7!FZEg^5VOj0;FE)/5CN"0/D/jN5C1h-jBPhU"
ARo4X?smAM@:EYR@:3JO@:<SO?smAM?smAM?XI2K?smAM@:3JM?sd8J?smAM?sm;J
?XI/J?t!JQ@:<SQ@:<VR@:<SQ?smAM?smDOh#CjZs'T:8P[^*T?tB4D@:Jt=PlLYi
@JXD@@:B+E@DDeOqjCr[s))6Ei*`#J@:3ODq2\omqNbT)r+'2B?hRr9OniFuq-Ul1
?t5;n?t&t@Gk?>lq-dq7@q&jANaZD5r7#1hpg7K;rG?"QrVhU\O8!(/rih.UP$n.R
@As*2?X[DTAR](U@:E_WAnc.)LlI1DPF/5(J:`?#G]\%HDf'?.G'emuP*qi-UR.sZ
V50ueWi;ttXfSV*Xfee/YHYC@Za-mDZEggCZF.'H[Bd!=W1olMG&hG9Ci"$,E-$,A
D/!]rAnu7"An5=X?smAN@:EYR@:3JO@:<SO?smAM?sm>L?XI2K?smAM?smAM?XR8L
?XI2J?XR5J?smAM?t!JP@UW\R@:<SQ@:<VQ?XR8L?t!JPanT:Qqu1#9rqZA'@.X&"
@:K4DP5eou@/jVD@:PAup\nf:Ie*;Mq/0YNs7QA(?t!LBrF'/DqZ$EdG%=ug?Ma]u
qdX$Xr*]O(q>L?kmU5lu@<c0fs']U?@:<UENacJ3q-d`HrF')Ao5A#Fl1SRpGj8gK
B)2FBAUa#R@@[$u?t!MUARSqP@U`eVB52C/JV/&kTr58ZJ:iE$G]RkGCi+*-H%Up*
S=?%BTVJThV50ufX/r>#Xf\\+Y-5(6Z*:R@Za7!DZa-pD['[3I['R*CVkp,WGB.M8
Ci"!,FEMkQEGfT+A85mqAn5:W?smAM?t*PQ@:3JO@:<SO?smAN?smAM?smAM?smAM
?sm>L?sm>L?!grH?sm>K?smAL?t!JP@UW\R@:<VR@UW\R@:EYS?t!JP@:<SR@:<SP
?XI/H@:<PO@:EYQ@:<SP@UW\S@UW_T@qK=b@preS?smAK@:*AM?t!OEqI*`?@:3MP
@:3DJ?=$rE?XI,I?XWnA?t!J\lX4%*@UWYP?smDO@UWYP?sd8K?X[DP?sm>L?sd;L
?t!JO?t*PQ?smAO?t!JQ@:<PO?!UiF?XR2GAS#FgEHch`M1g88X/<h&J:DrnF)l;A
G&_;<I"-a'R[Tb;Su/TmY-"e-Xfeb.YHY::Z*CXAZaR<L['d<LZa6sEZa@*HZEpmC
Z*:I;PD=I*DJjB2F`qqPF)Yf'AS>glAR]1_?smAN@U`bS@:EYR@:<MM@:3JO@:<SP
?XR;M?smAM?XR5K@:*AK?smAL?sd2F@:<SR@:<SQ@:<VR@:<SQ@:EYR@:E\S@:3MP
@:<SQ@:<SP?sm>K@:<SP@:<SP?t!GO@:E\T@:<VR@qB4`@preS?smAL?smAM?t0'"
?t*SR@:3MP@:<PM?=$rG?X@&H?smbY@:<PRCLLRW@:ESN?smDO@U`_Q?sd;L?=@8N
@:3JN?smAM?smDO?t*PQ@:3GO?t!JP@UWYO?!q&J?sd;IA7]IlEHZ_[M1U>OQaO_s
LkgJ*F_u,PHuj=PItNN8St;ODTr+loYH=q.Xg"q2YHY=<Z*L^A[C<TP[^W]RZEggD
['d<LZa7!DZEg^<S;i)EEc,`3EH6/BFE))-A7]FeA7/hW?smAM@U`bS@:EYS@:3GL
@:3MP@:<PO?XR;N@:3JM?XR5L@:*AK?smAM?X@&F?smAM?smAM@:EYR@UW_S@:<VR
@:EYR?smDO@:<SQ@UW\R?sd;K@:<SP@:<SQ?t!GN@:<SQ@:<VS@V'.`A78kS@:3MN
@:3JN?smAM@V&tW?t*SR@:<PN?sm>L?XI/J?smDO@UNVQ?smAM@UWYO?XR;N@:<SP
?sd8K?XR>O@:3JN?smAM?smDO?t*PQ?smAN?t!MQ@:<PO?smDN@:<MMAS,^qEdE4d
MLUVYPK(q4M2-Y.FE2\oIr]g`K85PKT:VUBU8FuqY->.4Y-G.3Yd1RBZF73L\@8rW
\%&rXZE^[@ZaI3KZa6sDZEg^<UR6mgGAh>8Ci=<6F)u85@q9.]@UW\T?smAM@:<SQ
?t!MQ@:<PO@:3JN@:<SQ?XI2K?smAM?sm>M?sd;K@:3JN?sd8H?smAM@:<SR@UW\R
@:<PO@UW\S@:<SQ?XR8M@:3MP@:<PO?smDM@:3MO@:<SQ?smDO@:<SQ@U`bS@q9.^
A7B"W@:<SO?XR8M?XR;N@:<SQ@:<SQ@UWYP?XR8L?XI/J?smDP?t!JP@:3JN@:<MM
?XR;N@:EVP?sd8J?XR;N@UNSO?XI2K?smDO?t*PQ?sd;M?smGP@:<PN@:<PP@:3JN
AS5drFa\prN.I1ST#]<EM1KqoE-R+oG&MVVMj'HoS"-"AUo1B#Xfnq2Y-P74Z*UjH
[(!TV]!o2[\@B)ZZE^aCZa-sFZa-mBZa-j?WLf6+G]7M:CM[m-EcZ/5A7T7]@UNSP
?smAM@U`bS?t!JQ?smAM@:3JN@:<PO?XR8L?smAM?XR5L?sd;L?smAL?sd8J?smDO
@:<VS@:E\T@UW\P@:EYS@UW\R?smDO@:<SR?smAM?smAM?smDO@:<VR?smDO@UW_T
@UW\R@V'._AR](V@:3JM@:*AM@:3JN@:N_R@:<VR@UWYP?t!GN?sd5J?X[>O?t!DN
?sdAN@:<ML?XR;N@:<SP?s[5K?=@8O@:3JM?smAM?XR;N?t!MQ?smAN?t!JP@:<PN
@:<VR@:<POAS#UpH%_'0MMR:UTt\[?M26M#E-mIhG^=jrOHbupSXuLLVQ?r(Xg#"3
YI1a?ZaI?P[C*QV\[T,]\[]2[['[6J['R*FZa6sDZa-mAWhu)<H?3tAChmj+EcGr0
@qB:aA78kS?smAN@:EYS?XR;M?t!JP@:<SP@:<SP?XR8K?XR8L?XR5K@:*DL?t!GN
?XI2J?XR;N?t!JQ@UW_S@:3JN@:E\S@:<SQ?smDO@:<VS?XI/J?smAM?XR;N@:<SP
?t!GO@UW_T@U`bT@Us%]A7AtU@:<PM?smDM?smDN?XI2L?=.,K?XR2H?=.)I?XI,I
?t!JP?XI2L@:*GP?t!DL?XI5M@:<PO?X@,J?X[AO@:*AL?XR8L?smDO@:EYR?XI2L
?t!JP@:3JM@:3MP@:3JOA7TFoIYiu;N/<U]R_7(GM0s;aG)W&AGCP7&P*qf0T:VgV
W3!2,Y-G45Z*q*E[(!WT[^EZW]"5Ja\@/iRZa@*I['R'EZEggCZEgdAYH"(LI<TaN
Des6-E,TN*AS5[gAR]%U?sd;L@:<VR?smAM?smAM@:<PP@:<SP?smAL?XI2K?smAM
?smAM?smAL?=.)J?X[AN@:3JO?smDO@:3JN@:EYS@:<SQ?smDO@:E\T?XR5K?smAM
?t!GO@UW\R?smDO@U`bT@:<SQ@Us%\A7AtV@:<PM?smAN?sd;L?XI/J?X[8J?s[2H
?XI/I?sd8J?sm>O?=@2J?t!JQ@:<MM?XI5M@:EYQ?XI2J?=@8N@:3JM?XR8L?smAM
?t!JP?XI2L?t!JP@:3JM?t!GN@:3JMAn>^rI>No@NJj!eOfm07Mg0GfFGZ3/Jqf2G
R$jJ9T:_mVWN<;.YHb:7Z*La?ZaI<O[C<]V\[oA`\[JlPZEggDZa7!DZa6sDZEgdA
Z)aISIX?<YDf'?.D/F'$AnYjkB4>=Y?smAM@:E\S?XI2K@:3MQ?smAM@:<PO?sm>K
?XI2K?XR8L?sd8J@:<PM?XI2L?smAM?smDN@:<VR@:<SR@:<SQ@UW\S?smDO@U`eT
?sm>K?smAM?t!JP@UW\Q?smDO@UW_T@U`eU@Us"[@preS@:<SO?smAL?smAL?X@,I
?sd8K?=.&F?XI/J?XI,I?smDO?=7/K?smDO@:<PN?XI5M@:<PO?X@)H?=@8O@:3JN
?smAM?t!JP?t!JP?XR8L?t!JP@:3JM?sd;L?t!DMB4bmsHAIK<Mi*a`NL@AcMgKnp
G`.H5O-5]mR%9e@TUqgSXf\e4Yct=7Yd1X?Za@0LZaR?N[^`iW]"#2VZa-mCZa-pC
ZEgdAZa-mBZ)aOWJUMfaD/O3,Ci+!%BP;-pAn>F[?smAN@:<VS?X@,J?smDO?t!GO
@:<SQ?sm;I?!guI?=.)K@:3GL?t!GM?=.,M?XI/I?X@)H@:<SQ@:<SRA7AqQ?<poG
?sm>K?t!JP?XR8K?XI,H?t!GN?smAM?XI/J?XdGP?XR;O@U`eV@q&kT@:!;I?sd;K
?XI2K?smAN@UW_S@UW\R@:3JN?sd8J@:<PP?X[8K?sd>L?sd8K?t!JP?t!GP@:3JN
@:<VS@UW\R@:*AL?t3PL@:<PP?t!GN@:3JN?smDM@:<SR@:<VS@prqdH\[E9P)bN`
Lm,j/NJ)_+I%.+%NfoTjS"?=IWiN2'ZF%$EZa.$EZF@HV\$i]P['[0GZa@-K]"GP\
YHP.7Yck45Z*:I:Yct@9ZE^<jKmIu_D/F-,DJjB1D/Ep#@V8tS?smAM?smDN?XR;M
?smAM?t!GO?smAN?XI/I?t!GN?smAL?t!JQ?smAN?t!JO?t!GN?sm>L?t!MR@:<SQ
@q&eN?=$uH?sm>K@:<SQ?smAM@:<PO@:<MN?XR8L?XR8L@:<SQ?XR8N@UW_U@U`bS
@:*>J?XR5J?XI2J?smAM@:EYS@:<PP?smAM?XI2L@:<SP?=7,K?sd>K?XR5J?smDO
?t!JQ@:3JM?t!JQ@UWYP@:*DM?t3SM@:<SQ?t!GN@:3JN?XI5L@U`bS@:<VR@q'"e
HA.37PE(N[M3,^.ObndHN53c=S"Q%5S"-+DWiN2)ZEpjDZa.$GZ+.HX\@ArPZEpjD
[^`o]]Xt\\Y-5%4YHG%3Yd(F;YctC:Za-TtLO=DiD/F0.D/X?2D/<fu@VK.V@:3JN
?smDN?smAM?smAM?smAM?smAN?XI/J?smAM?sd8K?XR;O@:3JO?t!GN?t!JO?smAN
@U`hV@:<SQ@q&hP?=.&J?sm>L@:<SQ?smAM?sm>L?t!DM?smAL?smAM@:3PQ?=.)L
@UW_U@:<SQ@:*AJ?sm>K?XI/I?smAM@U`bT@U`bR?smAM?X@,J@:<PP?=7,J?sd;J
?sd8K?smDO?t!JP@:<PN?smDP@U`_P@:*AL@:N\O@:<PP?XR8L@:*DM?smAM@UW\Q
?t!JPA7K4hH%h$4OckfdLlf<sRu!#aTX;MP[&B@ZS=cOLXK8Y2ZE:72Za@0JZ+.HX
]"5>UZ*CR>YHbC?[C*<FXf\b/Y-"h/YctC:Yct@9['Ha'Ljs\oD/O6.Ci4-.D/O!$
@;'"U@:3JN?smAN?smAM?smAM?smAM@:<PO?X@,J?sd8K?sd8J?XR;P?smAM?t!GO
@:3JM?smAN@q9.\@U`bS@q&hQ?XI2K@:3JM?t*PQ?smAM?smAM?smAL?smAL?X@,J
?XR8M?=%#J@U`eU@:<SR@:*AK@:<PO?smAM?XR;M@:<SR@U`_Q?smAM?XR8M@:<PP
?smAL?XR8L?XR5K?smGP?t!JP@:3JM?smDP@UWYO@:*AL@:EVM@:<PO?t!GN@:3JN
?smDM?smDO@:<SQAn,CiH%_!4O->cgMitcuQ&(iiZd@.Qc`N_,S"?@KXKA_1YH+\'
Yd:aDZFIQ]]Y(_ZZ*:F9XKf"6Yct@8XfSV*Xf\_-Y-5+8ZEga>['H^)NIZA!D/=$*
D/X<0Ci*d!@VB.W@:<PO?XR8L?X[>M?t!GN@:3JN?t!GN?XR5J?XI2K?XI/I?sd;N
?smAN?t!JP@:<PO?smDPAS#Ib@q&kT@q&hQ?XI2K@UNSO?t!GN?smAM?smAM@:<MM
?sm>K?=$uG?XI2K?=%&L@UW_S@:<VR@:*>I@:3JN?t!JO@:<SR@:<SQ@UW\Q?smAM
?XR8L@:<SO?=@5L?smDM?XR5K?t!JQ?t!GO@UNSO?smDO@:<PO@:*AL@:EVM@UW\R
?smAM@:3JN?smAM?smDO@U`bSBP(jnGD1m4OHkuhP*`etKSPbGXmGN6`MT5uSt2RK
X0&7oUS=N[YHkI=ZF@N`]t:b]Yct@9W2Q\oW2ZhrXf\Y%V4s]^XfSY,YHP17['6R*
Q%OL,Ci!m'D/jN5Df96'@;'"U?smAM?XR8L?t!GN?smDN@:<SQ?smAN?XR5K?XR8L
@:*DL?XR8M@:3MO?t!JP@:<SP?smDOAS,Oc@q&kT@q/nS?XR8L@U`_Q?t!JP?=$uG
?sd8J?smAM?smAM?=.)I?sd;L?!guK@UW\Q@:EYS@:!;I@:<PO?smAM@:3MQ@:<SR
@:EVQ?smAM?smDO@UNSN?XI2K?sm>K?sd8L@:<SQ?t!JQ@:3JM?t!MQ@U`_Q@:*AL
?t*ML@:<PP?sm>M@:3JN?smAL?t!JQ@:<SQBP(jnH%_$5Od;2lNL?uZMMd@R]BeY+
Y+M2ST:MC7R@ft:S"Q[WZ*CR<Za[Zd_S*LiZF$pBZ*(1-Vk^&bWiN+rU7RpJUSb&n
Xf\b0ZEU@*R"p*.DJX'%CMn!+CMRKq@qf:X@:3JN?smAM?t!JO?smDO@:3JN?XI/J
@:3JM?sm>K@UNVO?XR8M@:3MO?t!JP@:<PO?smAM@q0"Y@UWYP@q/qT?XR8L@UWYP
@:<SP?XI,G?XR5J@:<MM?t!DL?XI2H?sd;L?!^oI@:<SP@:<VS@:*AJ@:3JN?smAM
@:<SR@:<SQ@U`_Q?smAM?smDO@:3GL?XI2K?t!DL?sd;M@:<SR?t!JQ@:3JM?smDO
@UWYP?sd8K?t*ML@:<PO?smAM@:3JN?smAL@:<VR@:<SQC1_'qG_V*7OctrfMO's<
Nf8n4lgrN%Un4!DS!K1sOdVi<WN`P-Yd1O=Za[Wb`5''s]",>[ZE^[=YcY(2Xf\_-
XKAV,Xf\\+Xfek5Za$O*RZ2c9E,B?'Bl.g0DK]i4@qf=Z@:3JN?smAM?smAM?smDO
?t!GN?smAM?smAL?s[/H@UWYO?smAN?smDN@:<PO@:3JN?smAM@U`eT@UNSO@q9"U
?XR8K@:EVQ?smDN?XI2K@:3JO?t!DL?sm>L?=$rD?!q&J?!^oH@:<PO@:EYR@:*AK
@:3JN?smAM@:3PR@:<SQ@:<SP?smAM?smDO?sm>L@:*DN@:<MN?XR8M@:<SQ?t!JQ
@:3JM?smDO@:EVP@:3JN?t3SM@:<SQ?smAN@:3JO?smAM@:<VR@:E\UC1_*rH&%?:
QBIDhL6IpsNJs(go]=&_TUqaJQ'%2mQ_C:XXg#(8Z*CO>ZaRTa`l#U&_Rm=f\@8oS
['I$EYHkRD[BZs?Z*:F9YctC>[Bls/S!8JLDJX'%CiX`HJrG,$@qf=Z@:3JN?smAM
?sm>L?t!JP@:<SQ@:3JM?sm>K?sd5I@:EYR?sd;L?smDO@:<PO?smAM?smAM@U`bS
@:3JN?sm>L?smAM@pr_P?smAN?XR8L?smAL?XR8L?t!MR?sd;M?t!GN@:3PQ@:<VQ
@UW_T@UWYO?XI2K@:*GO?XR;N@:E\S@:<PO?smAM?sd8J@:<SP?=.,L?X@&D?XI2L
@:<VT@UW\R@UW\Q?t*PR@:<SQ?t!JP?sd8K@UW\Q?sd8J?XI2K?XI/I?t!PXB4b^f
@q':eF`ib1P*1ibNgGukMh\4mp<p":TV/$QStN'_XKJb5['d6KYct@9ZaRN`_SO()
_7R+`[^<?EXJ_nkWN*5+\@/uX\%95`\@8oTZ*CR6W18]hF)5W-Eg!/mV5TrWGApno
?XI/I?XR8L?smAN@:3MP@:<SP?smAM?sd5I?=$uG@:<\V@:<PP@:3GM?t!GN?smAM
?smAM?sd5J?t3_Z?XI/J?sd8KA78kR?smAN?XI/J?sd8K?XR5J?smGQ?sd8L?XR5K
@:<VR@UW_S@:3ST@:<PN?sm>L?XR8M?sd>N?t!JP@:3JN?XR5K?=.)I@:EVP?=7/J
?sd5I?=.,L@:<_V@:<VR@:<SQ@:<SQ@:3MO?t!MQ?sd>L@UW\Q?sd;L?sm>K?s[2I
?X[DUB4bagARfUjFEN_7R[KM(NgPleMN,L6hR05UTq7jMUSt5sWNNA+Yd1O@XK/D'
YI1pW`59=(^UUYWZEpj>VP9B>QD1+BWiiY:[^j#[\%&uXZ*LX;VO`WjF_YQ/JYB-J
XK8%eIs#+(?sm>K?XR8L?smAN?t!JP@:3MO?sd8K?XI,H?X@)H@:<SS@:<SR?smAM
?XR8L?smAM?smAL?XI,G?t!PU?sd;K?XI/JA78hP?smAO?<poG?sm>L?sm>L?t!MQ
?XI/K?sm>L?smAO?t*ST@UW_T@:<MM@:3JO?X[AN?XR5K?sd>M@:3JN?sd;L?s[2J
@UWYO?XI2J?sd8K@:3JN@UN\T@UW_R@U`bT@:<SQ@:<SQ?smGP?smAM@:<PO?sd;K
?sd8K?sd5I?X[GVB4Y[cARfRiFEEP4VOa-BQ^W_uOJC:[`2]Z1U7e-RV59r`USOcb
W2lr"Vl$2fX0T7P`P]I']XG,LZF$j8TTOq\J!6CaP*i2LYHkRF\@]>]ZEga=VOrs!
E,9?0NMs.hW2lM_L3?s3?XR5J?XI2K?smAM@:<PO?smAL?sd8K?=.&G?XI/J?smDO
@:EVQ@:3GM?smAM?smAM?sm>K?=$rE?t!PT?XI/J?XR8KA78hQ?smAN?!^iE?XR5L
?XR5K?smDN?sd8L?sm>L?=.)J@q0%Y?XR;N@pi_Q?smAM?X[>N?XR2J?s[2I?t!GM
?XR;M?smDO@DMVH@/]+o?sd5J?X[AO@K645@:<SQ@UW_T@:EYR@:3MP?smDO?t!GN
@UW\Q?sd8J?smAM?XI/J?t!MSARf7\AR]LfF**D2XJ;DSS!fD4ZdI@R\>uC#US=NU
P)5!NLle1$TqnKZT:2(8VQI/9`597"]!\cCZ*UU4S;VoHG*&#OU84?KWiWG0[(3`U
ZEpg>VOj*)E,BE1S?B-&Y-+FmN-Sl@?smAM?XI/I?XR8L?smDO@:<PO?smAM?XI/I
?XR8L?smGQ@UWYQ@:3JO?smAM?smAM?smAL?=$rF?smDO?XR8K?XR8L@pr_P?smAO
>[:ZC?sm>K?sm>K?=$uH?=.&I?sd8K?=7,K?t*VT?XdGR@UW\P@:3JN?t!GN?=%#I
?X[8J?t*MO?smAM?X[>N@:9-*q#=]/?t!JP@:3JN@GpW`@:<SQ@U`bT@:<SR@UW\R
@:<VR?t!GO@:<SP?sd8K?XR8K?XI/J@:<VS@q&nV@q'4aEH7#-Unjo[SX6=pf'V5?
]Wn<,V4O*4JpMlpJVK>NOH,6WO,]<dT;J]q^;7Lp[Bcj5Yct1+SWek\HA[uTVQH\V
RA-dbYI(^GZEg^>WM>r;EboW:S#39kYd(%%Nd>/C?XI/I?sd8J?smAM?smDN@UW_S
@:<VR?XI/I?=72L?smDP@:EYR@:3JO?smAL?smAM@:<SP?smAL?sd8K?XR8K?XR8L
A78kR?smAN?!UcE?sm>K?t!GL?X@)I?!^lG?XR5J?t!GO@U`bT?sd>P@:<PP?sd8J
?XI2K@:3JN@:*GN@:3JN?X[>N@:<VS@UWYP@:<MM@UNVQ?t!GN@:<VR@:EYR@UW\R
@U`bS@:<SQ?X[AO@:3JO@U`_Q?sd8J?sd8J?XI2J?XR>Q@U`bS@:3k]E-%&0VkU#_
T:E7&g$[_C_lTQ$Tp:UoNeMq3JqAf2JqSo8Mi3XVRA?db\%9/\ZEC1+ZEU<qOc,!H
I?'\]TVA0LT:_p[Y->:@Za7$DWhZ)HG&2&<KV>BGYHaq%NdPAG@:<PO?XI/I@:<PO
?smDN@:<SQ@:<SR?XR5J?XI2K?smDO@:EVQ@:3JO?sm>K@:<VS@U`bS@:<SQ@:<MN
?smAL?sd;L@pr_P?smAN?XI2K?smAL?smAK?X@,J?!UfE?=.#G@:<SR@:9-,?sd>U
s05s>i;<BNq-[K7@:EVQn,<(^q-dZ<B`Ir+s.s14s7p)2@&X+j?c2g?rUp3j@/fh,
@preS@U`bS@U`bS@U`eT?t!JP?t!JP@:<PO?sd8K?smAM?XI/I?XR>P@UihT?XIMW
EHRD9Umn0[St)[me`to4^8RZpOcYosPD"C;K7JT%I"$['Mi!@MP+\VMZ*L^BYHFn)
Z*:I5T9bOuMi=!iR@0\@WiE)"XKT"=ZaI0EXehVVIW9.CH_@@;Z*L1(MKr`@@:<PN
?sd8J?smAM?smAN@UW\R@:<SR?XI/H?XR8K?sd;L@U`_R@:3GN?sd;L@UW\S@:<SQ
@UinX@pi_P?XI2J?XI2K@prbQ?sd8L?smAN?sm>K?XR5J?=$oC?!UfF?=.#G@:<VR
@:Sj-?XR;Vr2O.]rQnnbrUF6$@:<^%qt+<GqYsr1s7p&0q"nT1p\/'(@/p&c?tEs"
rb5nR@f?+1@preS@U`eT@:EYS@U`bS?smDO@:3MO@:<SP?sd8J?XI/J?XI/I?XR;P
@U`bQ?X@GTF**S=W2?PkUS"<te)Sfp\u_a(R?3W!LkCA7JTu]kIXm!$NJi^VOdr,@
Xfo"7Y-"_(YctC7Whl>[S"-%@U84Z`WNND+Y-54?ZaI0DXeq_]J9,UKGaYD.Za?O,
LO*K;@:<SO?sd8J@:3JN?smAM@:<VS@:<VR?sm>K?XR8L?!h#J@:<SR@:3GN?XR8L
@:EYR@:<SQ@q0%[A7K"S?sd;M?t!GN?XR;N@UEDH?smAM?sd8I?=7,J?sd5I?XI/J
?smGP@UW_R@U]!/?t!GXqlO=9@UNSOr;'c.@:4$Os'T8D`W'=S@:<PPD>TQ*rr-;5
rV-3S@:3Nfpg@H9@fQ:5@q&nU@:<PP@:<SQ@U`bR@:<PN?XI2L@U`bR?XR8M?XI5M
?sm;J?t!MR@UWYQ@U`eWCNkMqT;AH`Tq\-jjRLd:Yc#%FYF^l=P*2&pObngDJ:N0"
L5(D8MjL6=YHY43X/i>&Z*1C9Xf\b/Xfen5Z*UaE\$i`QZE^^CZ*^jDYH+OrOa2%j
IYO;f[^W<9KQq*>@:Wt\?sd>O@UW_T@:<SR?sm>L?sm>L@U`_Q?XI8O?smAN@:3JM
@:3JN?XR;M@:E\S@UW\R?=7/K?smAL?XR8L?smAL?smAN@:*>G?XR8K?sm>K?XR8L
?XR2H?XI/J?t!JP@U`bT?t&j1q#C'er30R:DWLWjqu:)3?smC=ojD3:@:<PO@ClL2
rV_dbr;9p+s'Yli?smKbra9)?@.sV.@UW\S@:<PO@:3MP@UWYP?t!GN?smAN@:<SP
?smDO?sd>N@:3GL?smGQ@UW\R@q&qZCNkJpUo(#dTVA$dk4.$@^;8[S\"T=]R[T\4
P)+jEJUrE'L5(>7M3Oa6YHP.2X/i;%Yct@9YcY(2YHP7<[C3HL[^EQOZa6sEZa6sD
Y,eIsP'_@tJr5eaYI:F/K6Lp;@V04`?smDO?smAM?smAN?sd;L?smAM@:EVO?sdAP
?t!JO?smDN@:3JN?t!JO@:EYR@:<SQ?sd;L@:3JM?smAM@:<MM?smAM@:*;F?XI/J
?XR8L?XR;L?smAK?sd;L?t!JP@:3MO@q#*(Y.D9^s05trp]#PSqYFT-@:3OBpKq?;
@:3MWo_jnjG5[M1s8$0nDdiP7@UW`hr*j&A@K$.5@UW\S@:<SP@:3MP?smAL?t!GN
?smAN@UW\Q?smAN?XI5M@:<MN?smGQ@UW\RA7T1_Cj:YpUnji`Tr4WqiU,@<dadEn
YG@_\T:V[IQ&LNQJUr?&Knb;7MNaX2Y-5%1X/rA'Yct=8YcY(2Yd(OA['d6G[C*HL
ZEpmCZEpjBYH+\%R"9O2Lm!seWjAS$J95@6AnPdg@:*DN?smAM?smAM?sd;L?XR5J
@:<MM?XI5M?t!GO?smDN@:3JO?X[AN?sd8K?XI2J?sd;L?smAM?X[>M?smAL?XR5J
?sm;G?!^oG?smAM?=.,K?XR5J?smAM?t!JP?t!MP@Uf-3@:3PUr2sK'rEs#>p]"W.
?smCBs'K/Bi;I*Zr*Nl>M#ETJq=sd\@:Alt?XR<bpgIW@?i9\+@:<VS@:<PO?smAM
@:<PO?t!JO?smDO?t!JP?smAM?XI5M@UWVN?t!JP@UW\RA7T:aCNG#_TV8*UUnslu
kj[9Ehpp>^US4?SSt;OER#d,[JV&B$L5(D9Mj'[.YctC6XKAP)Yck:7YctC9ZEpsH
['[3J[C!9FYd1R?['d6HYH4b)S:u36K8P_NUTU>dI<&n2ASPpj@:*DN?smAM?smAM
@:3GM?sm>L@:<MN?XR;O?X[>N?smAM@:3JN?t!GN?smAL?sm>L?sd8K@:*DL@:3JP
?smAK?sm>K?sm8G?!^lF?sm>L?!guI@:3GL?XI2L?smDO?=.,L@Uej&?XR>TqlsQ-
qgMrCs8$/2?smBdq"eI4s7g$*rUaQIrqVI\rr;n(@:Jrn?smBcraT;D@JTq1@:<VR
@:<PO?smAM?smAM?smDN?smAN@:<PO?sm>L?XI5N@UWVN?smDP@:EYRA7T:`C2eKN
SY2^PUnONijR:jRo?>%KTqJ*SU7n9PSW8P^LP1;3Knb>9MisX-Yct@7XfSV)Xfnq3
YHY79Z*L[@ZEppFZa6sBZ*L[A[C!<HYHG%/TTXkRH@_'?Tqe'JH#mG)Anc!l@:!>M
?smAM?smAM@:3JN?smAM@:<PO?XR;N?XR;N?smAM@:3JN?XR8M?XR8L?sm>K?sd;K
?XR8L?t!PS@:3GL@:3JN?sm>K?=.)K?smAL?=.&I@:<MM?XI2L?smGP?!^oJ@:8cu
?X[>Vs/B@4pAF`In,-R#@:3JO_>X3*q-[T<p%\=\CAj?'s8$bC@:Ail?=@9cr*WuA
@/K\+@:<SQ@:<PO?smAM?smAM?t!JO?smAM?t!GN?sm>L?XI5N@UNPN?t!JP@:EYR
@q9%[BPhp>R[p(HUS"6ekOI'NiOQ=pUna]ZU8"?USWSbcLPUV:K8,,:Ng$$1Yck:5
Xf\\+Xf\\.Yck:8YctC<Za-pCZa7$FZa@$E[C<NKYcb13VjrBbFErFoR$N\qFDtVr
AS>ag@UEMN?smAM?smAM@:3JN?smAM@:<MN?XR;N?t!JP?sd;K@:<PO?XR8M?XR8K
?sd;K?smAL?XI5M?smGR?sd;J@UWYP?smAM?XI2K?sd8J?X[;L@:<PO?XI/K@:<VR
?!^oH@UWVO?XR>P?smAL?sd8I?XR8K?sdAM?sm>L@:<VQ?t*JN@:*DM?X@,I?sm;J
?sd;M?XR8L@:<SQ@:<SQ@:3JN?smAM?smAM?t!JO?t!GN?smAM?smAM?XI5N@UNPM
@:3MQ@U`bS@:E_WASQ1+QC=A=Unacpe*#EEfWqc\UnaZYTq@sMT9G:mLPLM8KSP>>
Ng-$-Yct=5Y-+t2Y-"h0Yct@9YctC<Za7!DZa7$H[C*?J\[SrOYcb:9X.bAoEccJO
NL,BUD/3Ke@qB7`@:!;K?smAM?smAM@:3JN?XI2K@:<MM?XR;N?XR;N?sd>M@:<PO
?t!JO@:<SQ@:EYR@:<PO?sd>N?t*SS?sd8I@UNSO?t!GN@:*DM?XI,F?XI/J@:<PO
?=.&J?t!JQ>[LiI@:<SO?t!DO@:<SO@UWYP?sd>L?t!GN@:3JO@:3JO@:3PO?smDN
?XR;M?t*MO?sd>N?=7/K@:<SQ@UW\R@:3JN?smAM?smAM?t!JO?smAM?t!GM?smAM
?XR;O@:<MN@:<SR@:<SQ@UW_TA8,n#Pa\8>UnjZid,s9Tbc7nHTU_I>SXl=CT9PCp
M2-h>KntM@NKfj(Z*CL6Y-5(7Yck43YHY78Z*CR?ZEgjD['I'G[C3HN]",2SYcb:9
XJCo'E,T`=Lm`mGD/3Ne@:Nk[?sd8K?XI/H?XI/I@:3JN?XI2K@:<PN?sdAP?t!JP
@:3JN@:3MO?smDN@:<SR@:<VS?t!GM?XR;N?XR5J?sm>K@U`bQ?XI2K?sd8J?XI2K
?XI/J?smAM?XR5K?XR;Q@prbQ?sd8K?XR5L?smAM?smAM?smAL?XI/I?XR8L?sm>L
?smAM?smAO@:*DJ@:<PN?XR8L?XR8M@:E\T@:E\T@:3GLA78kQ?XI/I?!^lG?t!DL
?smAM?t!GO?XR;N@:<MM@:EYS@:<VR?t!MTA7T7^H@:I0S>)U[db!:6_m6ABVP9]Q
TV/!NTpLe!N/3:JL4t53K85AIZEgd@ZEppF[^NWP[C3HLZa@*G['[3I\%&oV\$rlU
[^NWNZa@*IZETmKGB8"VOH+^/Ch7'b@:<SR?smAL@:<SP?sd>M@:*DL?smAM@:<SQ
@:<VS@:3JN?smAL@:<SP@:<SQ@:E\T@:<SQ?smAM?smAM?sd;K?sm>L@UWYO?XI/J
?sd;K?XI/J?XI/J?smAM?XR8L?XR;O@:<SO?sd8J?XI/K?smAM?smAM?sd8K?XI/I
?XR8L?smAM?smAM?t!JQ@:*DJ@:<PN?XI/I?XR8M@:<SS@:<SR@:3GL@:<MM?X@)G
?=%#H?sd8J?XR8L?t!JP?XI5M@:<PN@:<SQ@:<SQ?t!MSA7T7^H@CL-S=lOYcI^S#
_Q^)=Vl$8cTV%jNTph4-N/N[VL5:G6Mi3UVYd:X@ZEpmD\%&rW\$rfR[^<EK[^WZP
\%&rW[^W`T\[]#Q['[3HZ`fmKG&hhSO,eU-CM7-b@:E\T@:*DM@:<VR?XI2K@:3GM
?sd;M@:<SQ@:<SR@UW\R?smAL?smAM?XI/J@:E\S@UW_T?t!JP?smAN?XI2K?sm>L
@:<MM?!^lF?XI2K?XR8L?XI2K?smAM?sd8K?smGP@UW\Q@:*AK?XR8L@:3JN?smAN
?sd8K?XR8K?XR8L@:3JN@:3JN@:*GP?sd8J@:<SO?XI/J?XR5L@:<SR@:<VR@:3GM
@:<PN?sd8J?=$uG?XR8L?smAM@:<SQ?XI5N@U`_P?smDN?t!JQ@:<VS@q91aH$b4%
PFJGQ`m`2\`j;kOWi;trV5'`]URda;NfB']P)P3]SWo5"YHbF?Z*L^C\%'#[\[],W
[^NTN['d<L\@B&X\@8rW]=>8U['d<KZa-BhH>dqMK84bmDJ3Kg@:<VS?smAM@:<VQ
?X@/K@:3JM?smAM@:EYR@:EYR@:3MP@:3JM?smAM?sm>L@U`eU@UinW@:<SQ@:3JO
?smAM?XI2K@:3GJ?=$rF?XR8L?smAM?smAM?smDN@:*AL?smAO@UNVP@:3GM?XI/K
@:3JN?smDO?sd;L?smAL?smAM?smAM?smAM@:3MP?XI2K@:<SP?XI/I?=7/L@:<VT
@:<VR@:*AK@:3JM?X@)I?XR8M?sd8K?sd8J?smAL?XR>O@:<MM?smAM?t!JP@:<VS
@:X"aH$k4#OIN/O^!=jLb.+^\YHFk(WMl_oUnO?NOcGQfR?!K*WM5lQYHY78Yct@;
['mKT\@8rU\@/cO[C3NP\@B&Z\[f5Z\[o;Z[^NQL[^`K3JT,[OI"6H^DJ3Hd@:<SR
@:3JN@:<SP?sd>M@:3JO?sm>L@:<SQ@:<VR@:<SQ@:<PN?smAM?smAN@UW_S@U`eU
@:<VQ?smAN?sd8J?sd;L@:3GJ?!UfE?smAM?smAM?smAM?t!JN?sm>L?sd;N@:3JN
@:3JM?=7,K@:3JN?smAM@:*AL?sm>K?XR8L?smAM?smAM@UNSP?s[2I@:<SP?XI2J
?=7/L@:<SR@UW\R@:*DL@:3JN?XI2J?t!GN?s[2J?XR5J?XI2J?XR;O@:<MN?smAM
?smAN@U`hV@:NtdJ:<!#Mj^NF\B`:Bb.+a\Yd(C2WN*#"VPKr^S<T2%QB@rKZDX[s
WNNJ0YctC:Z*UsP]=GJ`\[])X\[oA`\[]/[]",>[\@T8\[C!9H\\,2@KQ_N[H[^9\
D.d?e@:EYS@:3JN@:<VR?sd>M@UNSP?smAM@:<SQ@:<SR@:3MQ@:<PN?smAM?smDO
@:<VR@:<SR@:<SP?sd8K?XR5J?XI/J@:<MM?=.&H?smAM?smAM?smAL?sm>K?sm>K
?XI2K?sd8J?sd;L?=.&J?smAM?XI2K?sd8J?XI2J?XR8L@:3JN?smAM@:3GM?=.#H
@:<SO?sd;L?XR8M@UW\S@:<SQ@:3GL?sm>K?X@,J@U`_P?sd;K?sm>L?X@&G?XR;N
@UWYO?smAM?smAOARf4Z@:Ee`H$OdgMNk!@\&uq:a1&7VXf\\,WiN2$VP^/bTpV"-
R@C7u\ZDm:Yct@9Yct@9ZF%'P]tM(l]Xtbe]Y(nk]"5G`]">M`\%0)[['[3J]"PPL
N-TViG^+CPDJ3Ng@:<VS@:3JN@UW\Q?sd>M@pi\Q@:*DM@:<SQ@:<SR@:3MQ@:<PN
?smAM?smDO@:E\T@:<SR@U`eT?smAN?XR5K?XR5K@:<PN?XI/I?XR8L?t!GN?smAM
?sd;K?smAM?s[2J?sm>K?sd;L?XI2K?smAM?sd;L?sm>K?XI/I?XR8L@:<SQ@:3JN
?sm>J?!UcC@:E\Q?XI2K?=7/L@:<SR@:<SR@:3GM?sm>L?sd;K@:<PN?X@,I?XI/I
?=$uF?XI5M@:<MM?smAM?smDOAn>I\@:Ee`EHZYVLQ8.E[)1#/b.4aZXf\\+XK8J(
VPL&aV4Nj5SZ0<T]s+fK[C*BJZa-g>ZEpsK]Y(nj]tM(l^:q:p]tD"j]tM(k]"5M^
[C*EM\$riKSqME=G]I_EDJ3Nd@UW_T@:3JM@:EYQ?sdAO@prbR@:*DL@:<VR@:<SQ
@:3MQ@UNSN?smAM?smAN?t!MQ@:EYR@U`eT?smAM?sd8K?XI/I@UWYO?sd;L?sd;L
?smAL?smDN?sd8J?sm>L?XI2L@:*AK?s[5K?=.)J?smAM?smAM@:*DL?XI/I?XR8L
@:3JN?smAM?s[/F?<piB?t!JN?=$uG?=.,L@:<SR@:E\S@:3GL?sm>K?s[5K@:<ML
?XI2J?XR5J?=$rE?smDO@:<MM?smAM?smDPAn>I\@:Eb^DJsWBM2n=FZG"H)c+L9`
Y-+n0Xf\_/Vkp5eWhGZ;R&eN^]X"oW\@K/\]!o&Q[C*EO]"G_j^;%Cr^V@P!]tM.p
^V7Fq]tM(g[C*?H['?m>To=VYJ9Q$VDJ*Hc@:<VS@:3JN@:<SP?sd>N@preS?smAM
@:<SQ@UW_T@UNVR@:3JM?XI/I?XI/I?t!JP@U`bS@:E\T@:3JN?XI/J?sm>L?XR5I
>[(H<?XI2K?smAM?smAM?smAM?smAM@:3JN?sm>L@:*DM?smDN?smAM?smAN?t!JP
@:<SQ?smDN?smAM?smAM@:3JM?sd;K?smAM?smAN?=$uJ@U`bT?t!JP?sd8I?XR5K
?t!GM?t!DM?XR8I?XI/I?sd8J?=.,L@:<SO?smDO@:EYRCM76f@UWb\Df0Q>KTVe+
W3a1Ucc!H#Z*:F<Yd(L=['I-M[]uU!UT_2F\[SuY^qdh&^:_(h]XG;\\\#Vi^V.Ft
]">\m^:q:o^:q=r]Y1e^[(!HO\?iE=S;_rEG&V//BP:shARf.U?smAM@:<YS@:EYR
@UNYS@:<PO?t!JP@q0"Y?smAN@:3MP@:<VR?smAM@:3JO@:<SN?t!JP@:<SQ?sd8J
?sd8K?X[;K?<piB?sd8K?smAM?smAM?smAM?smAN?sm>L?sd8K?sd;L?smDN?smAM
?sd;L@:<SQ?smAM?smDO?smAM?t!JO@:3JM?XI/I?smAM?smAM?XI2M@q&kU?t!GN
?sm>I?sm>L?XR5K@:<PO?=.&G?XI/I?sd8I?!q)L@:<PN?smDO@:EYSC1q3g@UWe\
Ci+-;KTVe.Z*q]qc,[W)Z*:F:YHbF?[C*KQ\$`H:Vlm86[^EQY]YVJ"^r!q%_7I(`
]"G_i^V@V$^:h>!^V.@p^:h7o]tCk_Za@'G[^309T9+\VF)Pc+B4tjgARo4W?smAM
@:<YR@:<PP@pi_S@:3GM@UW\S@:<VR?t!GO?smDN@UW\Q?smAL@:3JO@:<PM?smAM
?t!JO?XR8L?sd;L?X[AN?sd8K?XR8L?smAM?smAM?smAM?t!GN@:<PO?sm>M?smAM
?smDN?smAM?smAM@:3MP@:3JN?XR;M@:<PO?smDO@:3JM?smAL?X[>M?smAM?XI2M
@q/qU?t!GO?sm>I?XI2K?t!GM@:<PN?XR5H?XR8K?XI/I?!guJ@:<PN?sd>N@:EYS
C27Ek@:<VVC2@g7LQ%V)aNiJacd0Y@Z`pX:Yd(RB[^`o\]=G2IYHY78ZF.3V^qmh#
\[AiV`5B6u^;.M$^;%M#_SO++_8![r]tV4p]tCk_ZEga=[Bm$4RtH!4DJX'%BP:sg
ARo=[@:EYR@:E_S?t!GOA7AtV@:3MP@UW\R?smAM?t!GO?smAN@:<SQ?smAM?smDO
@:<PN?sd8K?smDN?XI2J?smAM?X[>N?smAN?XI2K?smAM?smAM?smAM@:<PP?smAM
?XR5K?smAM?smAN?smAM?smAM@:3JO?smAM?t!JO?sm>L?smAN@:3JM?sd;K?smAM
?t!GN?X@,L@U`eU?t!JO?XI2H?XR8L?smAM?t*MO?XR5I?sd8J?sm>K?=.)K@:<PM
?smDO@:EYSC2.?j@UWbWB5):2LPq=neaD#1bg"/>\?W9BYHbIA\@K;g]!JZEY-G16
Wj9"B^VRb#[B?F7]=tqg^;.P$]tV;!`Pf[2_nj+%^:q=q]=bee['6[5YHY%#MfNfZ
CMR[!BP;!hARo=\@U`eT@:<VQ?smAN@prbR@:<SP@UW_Q?sm>K@:<PP?smDO@:<SP
?sm>L?smDO@:3MN?smAM?smAN?sm>L?sm>L?X[AO@:3JO?XI/J?smAN?smAM?smAM
@:3JO@:3JM?XI/J?smAM?smAM?sd;L?smAM?t!JQ@:3JN?smAM@:<MN?smAM@:3JM
?XR8K?smAM?smAL?X@,L@q&kU?t!GN?sm>I?sd;L?XR8L?t!GM?=.&G?XI2J?smAM
?=.,L@UWYN?smDO@U`bSC1q3h@q&qYBPML4LlIIheEk*!f$)@P^9t2LZ*LdE]">Vg
[]m!<XK/V2Vld88]"c%o]=,)S\[f8^^Vdt)]t_D"bK%Q>_8*e"^V7Fq\[f>^[B?Bj
Tq\$6G&1u9CMR[!BPD'i@q9%X@U`bU@:<YR?smAN@:<PO@UW\S@:<VQ?sm>K@:<SP
?smDN@:<SP?sd;L?smDP@:3MN@:3JM?X[>M?sd;K?XI2K?X[AN?XI/J?XI/J?smAM
?smAM?smAM?smAM@:<MN?XI/J?XR8L?smDO?sd;L?smAM?smAN?smAM?smAM@:3JN
?smAM?smAL?sd;K?XI2K?smAM?=$uJ@q&kU?t!GN?sm>I?XI/J?sm>L?t!GN?XR8I
?smAM?XI/I?=72M@:3JM?smDO@:EYRB4baf@q0(^Ci+*7KoM.b\\GAgeB61T^UC>J
Y->1:\@K2\['6d;ZE(16Yd(IA\A,hn^qm[m]=Ybj^Ve(.]t_D!ccF&D^q[Us^V@Ip
]",G^[]>[8H@p<UCMmp*CMR["BkV'h@:<SP?smDO@:<YR?smAM?t!JO@:<SR@UW\R
?smAM@:3JN?smAM@:<SP?smAM?smDO@:<SO?t!DM?XR8L?XI2J?sm>L?t!DL?XI,I
?X@)I?smDN?smAM?smAM?smAN?smAM?sm>L?smAL?smDN?smAM?smAN@:3MP@:3JN
?smAM?sm>L?t!JO?smAL?XI2J?smAM?smAM?XI2M@UihU?t!JO?smAJ?XI/J?XR5K
?t!GN?=7/H?sd8J?XI/I?!h#L@:<PN?smDP@UihU@q91`AS,IcDf9Q8K9).hY-PXP
dEU+a_n34VYctC<\%0#U['?j<Z*1+2Yd1[D[_'DraMu$-]"Gbm^V@V%^;.V"d)a,E
_83n#^:h7p\%0,][Af.-Cij?&C2[m(C27R!BkV'g@:3MO?XR8L@UWbS@:<PO?t!JO
@:<SQ@:<SQ@:<VR@:3JN?smDN@:<SQ?smAM@:3JN@:<SO@:3GM?X[>M?smAL?XI/J
?=7/J?!U`C?XI/K?smDO?smAM?smAM?smAN?smAM?sm>M?smAM?smDO?smAM?smAM
?smAN@:3JN?t!GN@:3JN@:<PO?smAL?sd;K?smAM?smAN?=%#K@U`eT?t!JO?sm>I
?sd5J?smAM?t!DL?=7/I?XI/I?XI/I?!guJ@:<PN?smGP@U`bT@q0"[AS#LgF)Po9
KT21lYdhu`b0.rTaM>6fZ*:O?]",>WZa$a;Z*:44XgGRJ]"Geq_SX.)]Y2+u`P]O.
^r!t'd`TJJ^qmh$^:q:o\@K;_Z)3"lBP2!nAS5amC27NuC2%9k@:<PO?XI2J@U`hT
?smAM?t!GN@:<VR?t!MQ@q9(Z?smAM?smAM@:<SP?smAM@:3JO@:<SP@:3JN?t!JP
?XI)H@:EVM?=$rF?XI/I?!UfF?smDM?smDN@:3GN?XR2I?s[2H?XR8L?t!GO?sm>L
?X[>O@:EVP?XR/F?s[2H?t!GO?XI/I?XR5K@:<PP?sd2F?sd;L>[:ZB?sm>L@:*GM
@:3JJ?!UcE?X@)G?sd8J@:3MO?sm>L?XR5J?t!AL?sd;L?s[/F?XI2L?t!MQ@q0"[
A7fOjA8,t,Jru.hVQIS3a4Aehe]ke7Yd:XA[^NNM['['AZEpa=['[?V]t:tl^:h7p
^V7P'_nX"%_SO.7f>P_L^r!q#^V.=o^:h7jYF'KIAS#LeAn>RgBP2$lC1q0hAnGUc
ARo4X@:<YS@:<SR?smAM?XI/I?smDO@:<PO@:<SQ@:<VR?smDN@:<SQ?smDO@U`bR
?smAN?sd8J?=-uG@:<PL?=.&H?=.&H?!UiG?XR8L@:<MN?smGN?X[>L@:3JM?XR8L
?sd>N?smAL?sd>N@:3MO?XI/H?XI,I?sm>L?t!GM?smAM@:<SO@:*DK?XR8J@9m2F
?t*MP?smDQ?t*JM?!^oG?XR2I?X6uF@:EVQ?sm>K?sd8K?XI5K?XI/K?XI,G?XI2L
@:3PQ@:E_VAS5[lAS?%.KTMIsY-5I.^<YK\f$(n:ZEgdBZaI3K['Hp>ZE^U;Za.!M
^:Lea]"5G^^:_8"_SF%+_84"9eAoMF_8=(&^qIFp]=u"iXHmmBB4YXcARoFfBP2$m
C1h*hAn>OcAn5=Y@:<YS@:<SR?smAN?smAM?smDO@UWYP@UW\R@:EYR?sm>L?smAM
?smAN@U`bR?smAM?sm>K?=$oF@:EVM?=.&H?XI,H?!^lF?t!JO?XR8L@:3GN?sd>N
?sm>L@UNSO?smAM?=.#H?=7/J?smAM?sm>K?XR5J?t!DN?XR8L?t!GO?smDN@:3DK
@:*DL?=@2K?smDO@:<SQ@prbP?s[2J?sd8J?s[5J@UWYQ?sm>K?XI2K?sd8K?=$uE
@:3JN?XI/K@:<SQ@:<VS@Us.dBPDU:M3""&WN`OjYL27ZdE987[Bd'D['m?JZE^X=
Z*CF:ZE^dH\$NEJ\@T5\]"5Sk_83t(_o0L@e&]JE_Sa7)^qRLp]tM%fWf:t3B4YR`
AS#LgB5)*pC1q3jAn>ObAn5=Y@:<YS@UW\R?smDO@:3JN?smDP@:<PO@:E\S@:EYR
?XI2K?XR8L@:<PP@U`bS?smAL?sd8K?XI/J@UWYM?X@)H?XI,H?XI2K?sm>L@:<PP
?t!JP?smDN?smAL@:3MN?smAM?XI5K?=72K@:3JN@:3DK?sd;L?t!GN@:3GM?smAM
@:3JN?smAL?t!JP?sd8J@:<SQ@UW_T@prhS?X[AP?t!JO@:3GL@:EYS?smGP?t!GO
@:EYQ?<piD?XI5M?smAN?t!JQ@:<SQ@:EbXCi"BJN00O+XhCTrT?l*:dE0>;[^3<H
[^NNJYct@9XeMSoZEgdG['R*G\\#Jb]=ktq_SF"(`5]mDd_s#:_Sa7,^V7Co]Y1k`
W.]##A7K(Y@qB4`B5DC!BkV'hAS,LbARo4X@:<YT@:<VS?smDO@:<SP?t!MR@:<PO
@UW\R@:<VR?XR8L?t!GN@:<VR@:E\S?smAM?sd;L?=.&I@:<PM?XI/I?=.&H?smAM
@:*JOARo:Y?XR8OAm\qS@!d91?t*YXAn5Ib?sd8VN+?:'@:NhV?t!JPAS#7W?t>.6
?smDRAS,RcA78tY@:*APA7/qY?smGTARJqXM0NH;@q/qZBOP=Y@q8t\AmetSA7o=[
A79h,@UNSP?smDN@:*DK?=.)I?XR8M@:3MP@U`bS@:E_WDf^;_P+%]7Y/QojPK22*
e',e?Za7$H['d6GYct4/VQ-f%ZEppE['[3M]"5J`]Y2%o^qdb&`lcHKc,%0/_ns:-
^V7Cn\@]G\Tm1?d@q&qXA7]=aBPq^(BkV'hAS,LcARo7Z@:<YS@:<VR?smDP@:<PO
?smGP@:<PO@:<SQ@:<SQ?smAM@:3MO@UW\R@:<SQ?t!GN?smAL?XI/K@:<PM?sd;K
?sd;L@$(1l?hpI*Pfj#6@:3IAqI*d;rVuciX^D#)o`+d^?XEd4p](8#@.sH6@:3O.
p%Vp'oDej_s'L3SoDJF]rEoT7?XMjlZ=;&"?srj-@:T'3s82G%@prfqqdNuCnb?M+
s']=6qI!_1X8N"to3c!Ara]I;jBu>"?X@#G?sm>L@:3MP@U`bS@:E_WE-HklR%0D8
^se[*Lp54Od`KD8['R-HZaI0HYcjq&YcP(5ZEgjE[^W`W]"#8\]">Pb]=Yksb0eAZ
a25U,_ns7+^:q:n\@]DYRrW:W@q0"YA7T7`BQ%g,C1q0iAnGXdARo7Y@:<VR@UW\R
?smAM?smDN@:3MP@:<PN@:<SR@:<VR?smAM?t!GN@UW\R@UW\R?t!JO?XR8K?XI/J
@U`_O?sd8K?smAMB^]J>o@I>WPPtB8?t&<qpLI_/\mJkFq-dZ>p\J3'?i0\-ARYUq
@/Ts!?smF?s7]uOqd<iApoe(6@J6-t?X`cH?Y'$2X^_5(?N9t3@:K7H?t004@UW\P
s+XrjqT`OJp0[^r?smC@nmPs:s7fu0O8iTqpnM2&>[1WD?sm>L?smAN@:<VR@:E_V
Ed<A#Sste4aj-9(I\"m5d`TSF\@/`M[C3HJYck+1YctC;Za7$I[^NZR[^<HM\@8oT
\%02f`luKOb/;!1_SO%)^:h1j\@K&LMfWZI@q0"X@q0(]B5VX)CM7<kAn>RdAn>F\
@U`hU@:<SR?smAM?smAM@:3MP@:<PO@:<SR@:EYR@:<SR@U`eT@:EYR@:EYQ@:<SP
?smAL?XR5K@U`bP?smAL?XI/Jp3L->s'K/BR/N`T@:0"IraB5C@Uj?Ps'oGFq=e9(
?iB8<It.Cj?iB!^Iq#DUqYjl1@:EqorkDlN@/lX'@:&fG@/YTN]jgg9rVBo0@U`bV
AU"+N?t!JPqY4K6rEs"0qs=5f?t!LDi*p,(r:j]/@+>$\@e"AB?<gfD?XI2L@:<MO
@q9+\@qB7aG(#:6T:Cq1f[cF:DNr8fg!7a]]XY>W[C3HKZ*:F9ZEgU:Z*_!K[^NWN
['HsA[^NZP[C!BR_8aC:beh35_8*h']tV+i\%&cDIrB%8@q0"Y@UinYBPq^*CM7?k
AnGXdAn>F[@UWbT@:<SQ?smAM?smAM?smDO@:<PN@:<SQ@:<SRA7K+Z@q9(Z@:EYS
@:EYQ?t!JP?sm>L?XI5L?t!DM?X[>L?XI/JpiU!Ej'Z5%P5eteCSLZ:qI*e.s7uHb
s'T8Cp&8?-@/Kojo^D;>@/SlUrF#PBqtsi7s82`brP)cK@/lO#?sroHiqd$^X^M2(
qu:&4@:T-,s7,j`@:<SQRf?d\s'T7,qYU(r@:<RDX^GRFr;U/4@a"RV@JtCY@:<VR
?XI2L@:<\X@q9._BPV9rIY*<8R[]M1g<,LtE.>%Da3;TE_n3C`\@K)YZ`pR1VkTi^
Wi2ku['[3JZE^^C[^NWQ[^NQO]"Pqtbf7K6_8=.-_7dFj]==u4G\q,+@UinX@q0"Z
BlJ!-B4YXaA7]:]@preS?smAM?smAM?XI2K?X[>M@:<SS@:3GK?sm>L?XI2K@:3JN
?smAM@:<SQ@:3JN@:<PO?smAM?XR;M?smAM?XR5J?X@,JC\qXNs3"eWPl"k;rr6nL
s'fpH@:<UEraB5CrVp85@.j)!?smDN?iT"ks,-Y\q>4S"qI!]=r4HHF@JH3t?srop
q-RP.Y[RM1?iKq1@bq&m@:0'0@UW\R@eX[5WF''5qI07"@:3IBqI!]>s7^#3ORush
rNTa<?sm>L?XR8M@:E\T@q&t\B52*oJ:iN:QBml*b,U)3CO)DsaNDT@bfIE']"GP]
Z)F7XR@0\HY-5%8Za@*H[C!9I\$rlY\@/lX\[f>faMbs4_83t(^qI=h]XF\rE,B<$
@q0"Y@q9(ZB5_^)BP(jeARo=[@:<SQ?XR8L?smAM?t!JO?smAN@:<SS@UWYO?sm>L
?sd8K?smAM?smAM@:<SQ@:3JN@:<PO?smAM?smAN?sm>M?XR5I?=$uI@%.+'@K2Br
PPSZqr;L)7q-mk5ggQEAqI*c>qtsl1?_$qf@B&s=?hNAccMri1s6j@]r+og=rP)cJ
@/Q@!?srp)MI9fdZ![J/?uH#/@BBKX@d<sh@Gq)k@K$*'@:<R<r*a.3qI*h.rV(+'
om^@_q.!n*k[7h,?smAL?smAN?smDO@q0(]AS#OhItriDQ'do*Y*F<PCNG?Ab/VWF
c-*f0]"PY_Z_a4YS"QabYd(I=['[0H['d<N\@T;c\[oDd]",Df`kfF+^VR\"^V.7k
]!S/^CM[To@UinW@q0"YB5hm-BOtad@UikU?t!GN?XI2K?smAM?t!JO@:<PP@:<ST
@:<MM?XI2K?sd8K?smAM?smAM@:<SQ@:3JN?smAM?smAM?sd;L?sm>L?sm>K?X@,K
?smAN?smDLP5ATnK5P%,pL.Ess88&Hs']AEs8?;4?snHTs8@%I?2rkk?\`#sq>Xl2
oDe_rrP)`J@J?'r?t''4?XR7@XCD&+?sp#.RpY1Jok"!u@_DSI@Vu#??smC?s']>o
q8$M7YcR`uTjV;:?t!GN@:<PO?XR8L@:<SQ@:<MN@q9+]B4YakKT;"UR@K>%RY>g'
D/surai2HKb/qK/\%K8YXeD;VTr5&tYd1R>['R-H[^Wi\]Y1qh]=ttl]Y22$`kfC(
^:q:q^V7=j[]Q'DC27<g@q0"Y@UikWAoD^+BP(gf@q/tV?XR8K?XR8L?smAM@:E_T
@:3GL@:EYT@:3GL?smAM?XR5K?XI2K?smAM@:<SQ@:3JN@U`bS@:<SQ?XR8L?t!DM
?XR5J?XI/J?XR5J?smAN?XI/I?t!DL@:3MP?X[AO@:<MO?t!JO@:3JN?t!GN?=.)K
@:<SO@:<PQ?sm>N?smGP?X[AN?sd;L?smAL?t!JN?X[8L?t!JO?t!GO@:3JO@($#W
?t!GN?t!MP@:3O:Z!h$J?XR5J?XI/J?sm>L@:*DM@:<SP?sd8K@q&kWB4YakNKB-c
R$NbkP_44$Ci"6T]#Vk7c-+);\\#DYX/)SkYHY47Yd:[B['d<N\@TAi^VI\!]tM(i
]"Z/)`5'+$]tV.n^V.4g[&T71C2.6g@UinX@q0"XASlF&BkM!k@q9(X?smAM?smAM
?smAMAn>O^@:*AI@:EYT@:3GL?XI2J?sd;L?=.)J?smAL@:<SQ@:3JN@UW\R@:<SQ
?sd;L@:<MN?sm>K?XI2K?smAL?t!GM?XR5J?XI2I?XI2L?sd8K@:3MP@:<PO?XR8K
@UNPN?<prH?t!MQ@:<SQ@:<PN?smDN?sd;L?sd;M?smDO?X[AM?smAL?smAM@UNVQ
@:<SQrVuOu?X@&F?XR5L@:<RBX^GRG?s[2I?sm>L?t!GN?sd;L?smDO?sd8K@q/tV
AS#OlNfB*iQAq/lNIc:nD/FHRVTR0)d*'DB\@/`LX/N##YHY::ZF76N[^WcW]"Gbn
^r"%)]tD"i\@oeu^:h7p^:q=q^:^n]ZDNS%C1q0h@q0"Y@q&nXA8H1!B4bgk@q/tV
?t!GN?smAM?smDNA7]=]@:*AL@:EYU@:<PN?XI2J?XI/J>[CcF?t!GM@:<SQ?smAL
@UW_S@:EYR?smDO@:3GM?smAL?XI/J?XI/J?smAM?t!GN?t*MO?XI,H?XI2J@:3JN
?smAN?smDM?smDM?!grH?sm>L@:<SQ@:3GL?t!DM?smAM?XI/J?X[;L?sm>L?s[5K
?XI/J?t!MQ@:<VQ@:*AK?X@)H?s[2J?smDO?XR;L?XR;L?X[;L?t!DL?sm>L?smDO
?sd8KARf4Z@V'4pOc,HqP*)&lM19bhDfpVfS\3@td)sDG]XP5QYck46Yd(L>[(!TU
\[f;`]tM.s_8=(&]Xkbf]">\m]Y1tk^:q=q]XY>SYbZtoC1q9o@q&qX@q0"Y@qfjp
B4bdlAS#C\@:<SQ?XR8L?XI2KA7f=\@UWYQ@:<SS@:3JL?XI2J?XR8L?!UcF@:3JM
@:<VR?sm>L@:<SQ@:<SQ?smDN@:<MM?XR5J?XI2K?=.#G?XR8L?smAM?sd;L?=.&H
?XI/J?t!DL?t!JO?sm>L?smAM>?kH@?XI/J?X[>O@:3GM?smAM?sd;L?XI2K@:3MO
?smAL?XR8K?XI2K@:<PP@UNSP@:EVQ?XR5J?sd>L@:<SP@:<PP?XR5J?sd;K?=.#G
?=$rF?XI2K@:3JOAn#1Y@:a5*T8o>,O.D>eM1BklF,#jDTW6,gd*9kT]!ScKZE^X<
Yd(L>ZaRBS]=Y\g^VI\'`l#X(]",Ga]",De]=kki^:q:o]XP5NYbHPeCM@Qu@q&qX
@q0%Z@;'RmAS,RhAS#C^@preS?sd;L?XR8L@UikU?t!GO@:<ST@UWVN?XI2J?X[AN
>[:]F?sm>K@:<VR@:3JM@UW_S@:EYR?smAM@:*AL@:3JM?XR5K?XR5K?sd8K?smAM
?smAN?smAM?smAM?smAM?smDN?XI2K?smAN?XI/I?smAM@:3MP@:3GM?smAM?smDN
?smAM?smAM?smAM?sd;L?=.&J?t!MQ@:<SQ?smAM?smAM@:3JN?sd;L?XI/I>[CfH
?sm>L?sm>K?smAM?smDN@:EVR@:<YSA7TV@RZ*r(Oc5!MKn+MpKVQGWQC"f.bgFAC
^pC/DXK]";Yd(I>ZF%'L\@K5b]Y;;'`P9'r\[fA`\%&u[]"#8[^V7@p]=bY_X.=QV
C2%BtAnGUbA7T4]@Vg!uAS5^lAS#@[?smAM@:3MP?smAM?sd;K?t!JP?smAM?X@&G
?XI2K?smAM@:3JO?smAM@q/qU?smAM?sd;M@UW\R?smAM?sm>L?sm>K?X@,I?smAM
?sd8K?smAM?smAM?smAM?smAM?smAM?smAM?smAM?XR8L?XI,I?smAM?smDO@:3JN
?smAM?smAL?smAM?smAM?smAM?sd8K?XI/K@:<SR@:EYQ?smAM?smAM?smDN?sd;K
?XI/J?!UfF@:3GL?smAL?sd;L?smDO@U`bT@:3SSA7ftOO,oorN/iUHL4=MuOi5hN
P`MEWcHjGG_mutQXK]":YctC=ZEppG[^`lZ]"5Pi^V.7k]">Ve\@K/]]"#;\^:q@r
]Xt\`Wg7jGBP;*nAnGXdA7T4]A8Q:#AS,UjA7]7Z?smAM@:3MP@:3JN?sm>L?t!JP
?sd;L?sd8J?=.&I?smAL?smAM?smAM@q9%W?smDN@:*DN@:<SQ@:3JN@:*>J?sd8H
?=.&H?sd8J?XR5K?smAM?smAM?smAM?smAM?smAM?smAM?XR8L?smAM?X@)I?smAM
?smDO@:3JO?smAM?smAM?smAM@:3JN?smAM?sd8K?XI2L@:<VR@:<SP?smAM?smAM
?smAM?smAM?XI/I?=7/L?sm>K?sm>L?XR8K?smDO@U`_R@:<VSA7fnEL67shO-#0T
KS+f+T?,$SR$O,;dE]VKahk?eYd:[CYctC<ZF%!H\%&uZ]XbVe]=PSc]"Pei\[o>^
]",>]]tV7q]Xt_bV2KP7C1_*kAS,RdA7]:^@r-*u@qB=fA7T4[?t!JP?t!JP@:3JN
?smAL?t!JP?smAL?X@&G?XR8L?sd;K?smAM?smAMA7K%V@:3MP@:3JO@:<SR@:3JN
?X@)I?XR2H?!UfD?sm>L?XR8L?XR8M?smAM?smAM?smAM?smAM?smAM@:<SQ?t!GN
?XI/J?smAM?smAN@:*AL?smAM?smAM?smAM?smAM?smAM?sd8J?XI2L?t*SS@:E\R
?smAM?smAM?smAM?smAL?sd8J?=72M?smAL?sm>L?XR8L?smDO@U`_R@:EYTA7fb,
J=)[dPEh,gL4ju&Uqj=<Um[L3[F!%Abf.#s[(!HLYctC<ZEppF[^`fV]",>_]=PYf
]Y1tj]",A_\[f8^^V.@n]=GM`TS%K-CLq'gAS>ahA7K.\@r-."A7K4cAn>L^@:<SQ
@:<SQ@:<PO@:*DL?t!MQ?smAM?s[2I?XR5L?smAL?=7/K?t!GM@:EYR?t!JP@:3MQ
@UW\R@:3MO?sd8K?sd2F?=$rE?XR8K?sd;M?=$uG?smAM?smAM?smAM?smAM?smDN
?smDN@:3JN?XI/J?smAM@:3MP?smAN?smAM?smAM?XR8L?smAM?smAM?sd8K?XI/K
@UW_S@:EYR?sd;L?smAM?smAM?smAM?sd8J?sd;M?smAM?sm>L?smDN?smDP@U`_Q
@UikW@qTOoJ>Jm"O-#B]N/)h,OJJkUTok.^S%6\dai;')\[]2ZZE^[?ZEpmE[C<WR
\@K/]]=btl]tD(m]"5J`\[oA_^:h1i\[]2[SU5?jB4GI`AS5[gA7T4]@r-1$A7K4c
An5F\@:<SQ?t!GN@:<PO?smAM?t!MQ?smAM?sd5I?XR8M?smAL?XI2K?t!DK@:EYR
@:<SR@:3JO@:<VR@:3JM?XI/J?sm>I?=$uH?sd;K?smAM?=.&H?smDN?smAM?smAM
?t!GN?t!GN@:3JN?sd8J?XI2K?smAM?smDO@:*DN?sd8J?XI/I?smAM?smAM?smAM
?sd;L?XI2L@UW_T@:<SQ?smAM?smAM?smDN?XR8L?XR5K?smAK?XI2K?sm>L?sd;L
?smDP@U`_R@:NeV@qTIhLomV?OGARIQ]cuJI#=2SM1KttKVPuqaiVK6]Xkbe[Bd'D
Za7$G\%&oU\@K2`]=u=t^V%=s\[o>^]=Y\e]t:ha\@K,XQ#LJMAn5I`AnPdhARf4\
@r-+#ARf7aAS,I^@:3GL?smDO?smAN@:<SP?t!MR?smAN?sd8J?XI2K?smAL?!grH
@:3GJ@UW_T@:<VS@:<SQ@:<SQ?XR8L?s[/G@:3GL?X@,J?XI2J?XR8L?<plE?smAM
?smAM?smAM?t!GN?t!GN?smAL?X@#E?XI/J?smAM?smDO?smAN?XI/I?XR5J@:3JN
?smAM?smAM?sd8J?XR;N@:<VR@:EYQ?smDN?smAM?smAM?XR8L?XI2J?sm>J?X@,J
?sm>L?XR8M?smDO@q&hS@U`eU@qTFjR]N0HObA1?S"c%!H$tU'F`hqLJrm"@^;Ih&
^V7Fo\$N?GZF%!H\@8oU\@T8b]u&%.^;%Fu]"5D`]=YYc]"5G^\[]&RK5#%4AS#F`
AnPdhA7T4]ASZ1!An5FaAS,I]@:*AL@:<PP@:<PP@:<SP@:E\S?smAM?sd8J?=.)J
?smDM?!grH@:3GK@:<VT@q0"X@:<SQ@:<SQ?XR8K?sd5H@:3GL?XR8L?XR8L?XI2J
?<poF?XR8L?smAM?smAM?smAL?t!GN?XR5K?!UcB?=.&I?smAM?sd;N@:3JO?XI/J
?sd8K@:3JN?smAM?smAM?sd;L?XR;O@:EYS@:EYR?smDO?smAM?smAM?XR;M?XI2K
@UEMM?XI2K?sm>L?sd;M?smDO@U`_R@:<YV@qTIsXf%GDMhZnDT?Od,L3eQ'E,p,B
H]45iY.DHg_8O4,\?`?DZEppG]!o/[]"5Sj^;eR:^;7P"]"5Jb]=YYc\[f8^\@JuO
I;3P1@q&t]AnPdhA7T4]BPMC!B4b[cAnGO]@:*AK?t!JP@:3JO@:EYR?t*SS@:3JN
?XI/I?XR5K?smAL?!^oH@:3DJ@:E_W@q9+Z@:<PP@:<SQ@:3JM?XI2K?X[>L?sd;L
>[1TB?smAM?smAL?sm>K?smDO?smAM?XR5J?smDN>[:]E@:*>H?!^lF?XR8L?XR8L
?smAM@:*JR@:3MO?smAM?smAM?smAM?smAN@:<SQ@:<SQ@:<SP?smAL?smAM?smAM
?XI2L?smAO@UWYP?smAM?smAM@:3JM?XI/I?XI2J>[LoKCik5k\t>.@J:E3#M8%N=
Q\'^.B4l=+M1q+\WMZZ(^VIe#[^!'@Xfo"7\$s#]]Y(tq_8sX4]Y2"m^:h4n]Y(qj
\[]>c]XG&AG]@A,A7T4]@qB:eBOtdgCN+64D.mHjB4kmiARf.W@U`_P?XI5L@:<SQ
@:3JN?smAM?sd;K?=$uI@:<SPA78nT@:EYUA7T7^A7T1Z@q&nU@UW\R?t!GM?XR8M
?XR8K?smAM?!^iF?XR8K?smAM?smAN?smAM?smAM?XI,H?t!GN?!^lF?sd5G?!^lF
?smAM?smAM@:3JO@:3MQ@:3JN?smAM?smAM?smAM?t!GN@:<SQ@:EYR@:<SQ?smAM
?smAM?smAM?sd;M?smAO@:<SP?smAM?smAM@:3JN?t!JP?smDN?!guPD0gr6_539C
I>*N.J>q2:VhB;5B4c4,OGf?lV5Bo_Z+S#h[^!'?Ycb49\$rr[]"Phq^Vdt&]=bhj
^V.@p]Y(qj]",Md]!e]7F)>T%A7T4^A7fLhBP2!mCiF?4D.mKnBP2!jAR](V?t!GM
?XI5M?smDO?t!GN?sm>L?smAM?=7/K@:EYQ@:<SQ@:<SQ@q/qV@q0"Y@q&kU@:<SR
@:3MO?sd;L?X[>M?sd;L?!UcE?XI/I?X@)I?XR8L?smDO?smAM?XI/J?X[>M?=.)J
?sm>J?X@&G?smAM?smAM?smAN?smDQ@:3JM?smAM?smAM?t!GN?t!GO?t!JP@:<SQ
@:<SQ?smDN?smAM?smAM?sd;M?smAN@:<PO?smAM@:3JN@UNSN?t!GO?smAM?X[GX
DgI>NeZ+^^J;&`0KV6K4]Sh#QB4l:/P`D'#W2-)\Wj&nA\$<0AZ*1I>\%&u[\A#\o
_8="$]t_=r^V.@o]Y(qj\\#Mf\?`#nE,99%A7T4]A7]CeBP;0tBQ%p3DJNouB4bgh
ARStS?t!GN?smAN?sd;L@:<PP@:3JN?XR5K?=7/K@:<PP@UW\S@:<SQ@prhU@UinW
@U`bS@UW\R@:3JN?sd;L?X[>M?XR8L?!grG?XI2J?=.&H?smAN?smAM@:3JN?sm>L
?t!JO?XR8L?smAM?=.&I?t!GN?t!GN?sd;M?smGR@UWYP?smAM?smAM?X[AN?t!JO
?t!JP@:<SQ@:<SQ?smAM?smAM?sm>L?smAN?smAN@:<SQ?smAM?smAN@:3JN?smAM
?smAM?t*_`EI*G9Tot1\J;/`3L7G6BRtu6)B4l:-Nf06sVPKr[W3*2'['?m@Z*LaC
\@K2_]"Phm_SNt#^V@Ls^q@=n]tM.m]=YYb[BZBWDJa0&ARo=]ARf=cB4u*sBl@s2
Df'3$B4kpmAn#.U@:<PP@UW\R?sd>M?t!JP@:3JN?sd;L?XI2K@UWYQ?t!JP@:<SP
@:E\T@U`bS@UW\R@:<SQ?smAL?XR5K?XR8K?XR8L?XI/I?XI/I?!goE?smAM?smDN
@:3JN?sm>L?t!JO?smAN@:3JN?XR8L?smAM?smAM?smAM@:<SR@:3JM?smAM?smAM
?t!JN?X[>M?smDO@:<SQ@:EYQ?smAM?smAM?smAM?XI2K?smAN@:<SP?t!GN?smAN
@:<PO?t!GN?smAM@V'=nEI*4nL4Xr*K8,2AOIM)UFEMVBAnQ.(Ll.RnVPpAeWN<5%
Y-G:;Z*LdE\@T>b]Y(tm^;%Cr]tM%j^:h1m]tV4p^:q1gZ`BLAD/=!%AnGXcAn5Ib
BP;0tCi463DJa-$B4ksoBjtLZ?smAN@q/nR?sd>M?smDO@:3JM?XR8L?sd>N?t!DN
?smDO@UWYP@UW\S@UW_S@:<SQ@:<SR?t!JO?XR8L?XR8K?sm>M?sd8I?=.&H?=.#H
?sd;L?smDO@:3JN?sm>K?smDN?smAM?smAM?XR8L?smAM?smAM?smAN@:<SQ@:3JN
?t!GN?smAM?smDN?smDO?t!JP@:<SQ@:<SP?smAM?smAM?smAM?XI2L?smAO@:<SP
?smAM?smAM@UW\R?XR;M?smAMB5ML%Dg-MSIXQZpJUi<3T8n)9DK'K1AnH('L5D7h
WMcSgWN<2&XKJ_1Z*LaE\@K/\]Xkeg]Y2"m^:_+l^:h4n]tV7q^V..`Yc!_5E,TN+
BP1pfBP(miB4u*tDfK]5DJNouB4ksoBOYCY?t!MS@q&hQ?smAM?t!JP@:3JM?sd;L
?smGP?smAM?smDQA78hP@UW_T@:<SQ@:<SQ@:<SR?t!JO?sm>L?XR8K?sd8L?sd8I
?!grG?XR5J?XR5K?smAM?smAM?sm>L?smAM?sm>K?XI2K?smAN?smAM?t!GN?smAN
@:<SQ@:3GM?smAM?smAM?smAM?t!GN@:<SQ@UW\R@:EYQ?smAM?smAM?smAM?sd8L
?smAN@:<PO@:<PO?smAN@:<SQ?smAM?XI2KC2[m(DKpDNJ9u`pJ:WWQUOmE$GB7Y@
BP):,LP_@kWMu_iX0Ah1Xf\_0Z*L[C\%&oX]",Jc]tM.n^V@Iq]tM.o]tV4o^:^q]
X.P5pEc5c-B4tphC1q<qBPD:"E,ff6D/3ctBkV6oARStS?smGQ@pr_O@:3MP@:<PP
@:3GL?sd;K?t!JP?smAM?smDRA78kQ@:E\S@:<SP@:<SQ@:<SQ@:<PN?XR8L?XR8K
?XI/K?smAL?=$uF?XI2K?XI/I?t!JO?sd;L?XR5K?t!JP?XI/H?XI/I?smDN?smAM
?smDN?smAN?t!JP@UW\Q?smAM?smAM@:3MO?smAM@:<SQ@:EYR@:<SP?smAM?smAM
?smAM?XI2K?smAN?smAN?smAM?smAN@:<SQ@:<SQ?t!MQCi+$-F*DkTIt<,tIta0"
Nd,Y`H?jIMBP)=.Ll%RrX/MklY->15Xf\_-ZEgdE\@K)\]">Vg^V@Iq^q[Rq]tM.p
]tD%l^qI:bWgeZfEc>i/BPD-lCM7EpB5)0uEH#].C1q6mCMIQpA7AqS?smDP@U`\O
?t!MR@:EYQ@:3JN?sd;L?t!JQ?sd8J?t!JRA78kQ@:<VQ?t!JO@:<SQ@:<SQ?XI2J
?XR8M?=$uI@:<PO?sd8J?sd8K>@(WD?smAL?smAM?smDN?X[>L?sd;M?XI2J?smAM
?smAL?XR8K@pr_O?XI2K?smDO?sm>K?smAM?sm>K?XdDN?XR8I?XR8M@:<SQ@UW\Q
?t!GO?smAM?smAM?t!JO?smAN?XI/I?sd8J?XR8L@:E\S?XR8L@:ESPBk_6nAnYsr
ASZ(%Ed4+:ItDEHFa.b<Ch\$5LPht0Y,nV'Xfo%8Yck77Yd(OC\@B&Y\%0,^^:h4m
]=bbh^:_.o]Y2"k^qmXuW1nZ_F)Z#3Bl%R$C2%?pBPM<uBP;$kBP1piAnl'nA78kS
@:<PP@:<SQ@UW_S@:<VS@:3JN?t!JP@:<SQ?smAO?smAM?XR8K?XR8L@:<SQ@:<SQ
@UW\S?XR8K?smDO?=.&J@:<PN?sd8J?sd8J?!UfF?smAL?t!GN?smDN?X[>L?XI2K
?XI/J?smDN?sm>K?XI2K@pr_N?XR8K?XI5M@:<MM?smAM?sm;J?X[>L?XI/G?smAN
@:EYR@:EYP@:3JO?smAM?smAM?t!JP?smDO?XI/I?sm>K?smAM@:E\S?t!JP@:EVP
Bk_3kAS5amAnl.%ItiW+VjVL=KT(=qCM@p4LPhn.XfJG%Y->4;Z*:I:Yd1UC\@B&Y
\[oGd]tM+m^:h1m]=Y_j]tV4p^;.=qW1\EWDf0<'B4tsmC2.BoB5)-uBP2!lBkV*l
A7fOg@UW\T@UWYP@:<PO@UW\R@UW\R@:3JM?t!JO@UW\Q?smAO@:3JN?sm>L?sm>L
@:<SR@:<SQ@:<SR?XR5K?smDP?!guJ@:<SO?XI/J?XR8K>[:]E?smAM?smAN?smAL
?=@2J?sm>M?sd8J?XR;N?sm>K?=7/KA78hO?XI2K?smDO@:3JN?XI2K?sm;J?t!GM
?=.&F?XR8M@:<SR@:EYQ?smDO?smAM?smAM?t!JO?smDO?XI/I?sm>K?sm>L@:N_R
?t!JP@:<SOAnPagAnPglBPMI6N/Ejq]:!MSOf4:XCM@p5M2J.1XK/>$YHY@>Z*CR<
Z*CU@\@B&Z\\#Pf]tD(n^:h7o]t:ql^:h4m^;.7lVkA3RD/*cr@q9+^ChdZuBPD3u
AnP^gBP;!g@:a(a@U`eW@UWYP@:EYQ@UW\R@:<SQ?smAL?smDO@:<SQ?smAO?smAM
?t!JO@:3MO@:EYR@:<SQ@:<SR?sd8K?XI5M?=.)K@UWYP?XR8K?XR5J?!^oG?smAL
?t!GN?smAM?XR5K?sd;M?XI/I?=72L?sm>K?XI2K@pr_N?XI2J?XI5M?sm>K?sd8K
?sd8J?t*MN?XR8I?smDO@:<SQ@:3JN?t!JQ?XR8L?smAM?t!JP?smDO?XR8L?sd8J
?sm>L@:N_R@:<\W@UWYOBP:sgAS#OiC286`Q(64EadR'iRC/<!C1qa5M2nI6XfJM*
YctC>ZEga>Z*L[@\@8uY]"Gel]Y2(p_8!e$^:h7q^:q@r^;.7kV4MdLD/<ls@q0%[
D/*d!BP;'nB4YajBP1sg@:a+a@q&nW@preR@:<SP@UWYQ@:E\T@:3JN?X[AO@UW_S
?smAO?smAM@:<SQ@U`bS@:<SQ@:<SQ@UW_S?sm>K?XR;N?!grI@:<SO?sm>K?XR8L
?XI/I?XR8L?smAN@:3JN?X[>M?smAN?sd5G?XR8M?sm>K?=.)JA7AnQ?XI2J?smAM
?sm>K?sd;L?sm>K?X[>L?XI/G?XR8M@:<SQ?smAM?smAN?smAM?smAM?t!GO?t!JP
?sd;K?XI/J?smAM@:EYQ@U`kY@UWYOBk_0kB4bgkDh++;Vmaagd$AQmPHTs_BP;L1
MN4U7Wi<)&Z*CR>ZEga?Z*CU?\@B&[]Y(nj^qmn(_SX1+^:q=t^r""+^;.1gTU0Y<
EGoW+AnG[gCM@KsBkV0nB4bglBkM'i?t<q^@preS@U`bR@:<SP?smDP@:EYR@:3JN
?smAM@UW_R?smAN@:3GM@:<VRA7AtU@:<SP@:<SQ@:<VS?sm>L?smDO?=$uI@UWYP
?smAM?smAM?sm>K?smAM?t!GN@:3MO?X[>L?smAM?sd5G?!guJ?XR5K?XR8L@pr_N
?XI5K?XR;M?sm>K?sd;M?sm>K?t!DL?XI/G?smAO@:<SQ?=7/L?smAL?smAM?smAM
?t!JO?smDO?XR8K?sm>L@UW\R@U`eS@:E\VAR]4[AnG^hB52@,Ni&/'SZKlHd$/Ej
R'D?[BkVU3MiOd:X/`8(Z*:O>Za-jAZEggB\@9#[]Xkei_o9R2_83t)^q[\&_o0L3
]tUncT9!r/F)Yu0AnG[iBP;'nBk_6oAnPgnBk_3k?t3bZ@U`bR?t!JO?t!JO@:<VS
@UW_T@:3JN?X[>N@:EYQ@:3JO@:3GM@:EYR@U`bT@:EVP@:<SQ@UW_S?sd8K?XI5M
?=%#J@:<PO?sm>K?sm>K?smAM?sm>L?smAM?smAM?XR5J?XR8N?sd5F?!guI?sm>K
?XI2K@prbP?XI5K?XI5L?sd8J?sd;L?sm>K?t!GN?XI2I?smAO@:<SQ?XR8M?sm>L
?smAM?smAM?smDO@:3JO?XR5J?sd;LA7]7]A7]:]?smJVBkqX&A7T4`DKpo%YcibA
S?^8PbEcscQ_A_9BkV[7NfU3<X/`5)Za$gBZa7!EZEgdB\@9#[]Xkbh`Pog5_83q&
_84%0`Pod4]Y1\^SVqH)EGoW,AnPdiAnGamC2%ErBP;-sCM7Bp?t*YX@UWYQ?t!JO
?t!JO@:<SQ@:<VS@:3GM?t!GN@:EYR?smAO?smAM@:<SQ@UW_S@UNSO@:<SQ@:E\S
?smAL?smDO?X@,K@:<PO?XR5K?sd8K?t!DL?XR5K?smAN?sd;L?X[;K?XI2L?sd2E
?!q&K?XR8K?XR8L@q&eP?XR8K?sd;L?sm>L?sd8K?sm>K?sm>K?sd8H?smAN@U`eT
?=.)J?sm>K?smAM?smAM?smDN?smDP?smAM?smAMAS#C^A7f@]@:a4rI"6inBOtam
JX34@ZBg*4PJ,8^`gCU`Pa$<'BkV^9OHHT@WN*#'Za6sA[C!<J['I$E\$ro[]=Ybi
_Sa@0_8=((_SO13a2Z$5]tL_[Rtkp!Ci!fuAS,RgA7fRlC2%EtBk_9tCMRZu?t!VW
@:3JN?t!GN?t*PP@:<SQ@UW\R@:3JN?t!JO@UW\R@:3JP@:<PO@:3JN@:<SQ@:<SP
@:<SQ@:<VR?sd;L?t!JP?sd8J?XI2J?XI2K?sm>K?sd8K?XI,H?sm>L?s[5K?X?uC
?!UfE?!guI?sd;L?XI/J?smAN@:<PO?sd8J?XR5K?smAN@:<SP?XI/I?t!JN?smDO
?=7/K@U`eU@:<PO?XR8M@:3GL?=.)J?X6rC?!guJARo:]@:EYRAS#C_A8#dsFG?!>
NeDt1G&2D_SZ9Q3Y_IpqQ,Uk_c'W6^JV7uUEH?nmU7\N`Yd(L>ZaR<P[C*HP\@8uW
\$icU]=bkn^;In.^r!t+^VIb*_83q"]XYAQSpP9dBPD-nB4YU`B4kmkAnGRaAS#Fb
AnYjiBP(ddBPD$f@q9+Y@U`bS@q&kT@:3JN?XR8L?XR5K?XR8K?smDO@preS@UW\R
@U`eU@U`eT@UW\R@:<SQ?sm>K?XR;N?sd8K?sm>K?X@)H?sm>K?=.)J?XI/I?sm>L
?s[2J?X@&E?!^oH?=.)J?smAM?XI/J?smAN@:<PN?sd8J?XR5L?smDO?t!GN?sd8K
@:<SP?smAN?XR5L@UW_T@UWYO?XI2L@:3DK?XI2K?XR2G?!grHA7T1]A78nUAnGUg
Cit8cNfoHYKnbA/EG]rPJsigCW.T\SS'K0sfplenH[K[EFEN=nUnFlhYd(L>ZF.-N
[^NWR\$riU\$i`U]=bkn^r=72^r!t,^VI_(^qd^t]=5/LS9esaBPD0pB4POaBPD-n
BPD*kAS#FaAS5[gBOkXaB4tga@q9"V@U`eT?t!JP@:*AL?smAM?smAM?X[>M?smDO
@U`bT@:<VR@:<SQ@U`bT@:EYR@:<SQ?XR8L?XR;N?sd;K?sd;K?XR5K?smAL?!goG
?sd;L?XR5K?s[2J?sd2H?=.)J?XI2K@:3JN?=.)J?smAM@UWYO?sm>K?XI2K?smAN
?smAM?sd;L@:<PO?t!GN@:<SQ@U`bS@:<SO?XI2M?sm>L?sd;K?sd;I?=.&IAS#Fa
@q94dC2.[5L5h=^M2$\;I=d5tEbK*#F-;raTmqB3TZbBti1k.*GC+4DGBSarU8"im
Z*CU@ZaI9P[^EQQ[^W`T\@8rW]=kqo_oB[7^qmt.^qde(_8![p\[JfFRXApdCh[Ts
B4PRcCM7BqC2%BoAS#FbAnPdhB4PI^A7]:[A7AtU@:EYR?smAN?sd;L?XI2J?smAL
?smAM?smDO@:3JN?smAM@:<SQ@U`bS@U`bS@:E\S?sd8J?smDO?sm>L?XI/I?sm>K
?smAL>[:ZC?smAM?XR5K?X@)I?sm;J?XR8L?XI5L?smAL?=.&I?smAN@UW\P?sm>K
?XI2L?smAM?XR8L?sd8K?smDN?smDN?t!JP@:<PO@:<PN?=.&K@:3GL?sd;L?sm>K
?!q&I@Us"[ARoLjFao@4OH#$HIscZmGBeacFDYW%Bm+ltVL3E/Y0>,=ihgR-F*_eB
I!U^+U7ecqZ*L^BZaRBR[^NZR\$rlW\@8oV]=bko_o9U6_SX4/_84(-^r!n"\@/]E
SUtitD/3m"B4kdeCh[TtE,KN.BkM-oBPM<rARf1X@qB1Y@:<VS@U`bS?t!JP?smAM
?sd;L?smAM@:<SQ?smDO@:3JN?smAM@:EYR@U`bS@:<SQ@UW\R?XR8L?XR;N@:3GL
?XI/J?sd8K?sm>L?!^iF?sm>L?sm>K?s[5K@:*>J?XI2L?XR8L?sm>K?XI/J?smAN
@:<PN?sd8J?XR5L?smAM?XR8L?sd8J@:<PO?t!JO@:<SQ@:<SP@:<PO?sd;M?sm;J
?XI2K?smAM?sd8LA7T4`BP;=2MNjEcKS"`%IscTgF`MkUFDtl&BPMUUQ#UJh_9C-L
ii$g1E-Q><IXR68V4t6#ZEpmD[(*ZX\%&oV\$rlW\[T&X]=bkn`5fj:^r+%,_SO+,
^qmh"]"#)KTSdo5DJa*$AnGXfCMR["I=-<`D/!]uBPD6qAn5:X@q9"V?t!GM@:EYR
?smDN@:<SP?sd;K?XR5J?t!JP?smDO@:3JN?t!GN@:<VR@:<SQ@:<VR@:<SQ?XR8K
?XR;N?sd;L?XI2K?sd8I?XR8K?<poG?sd8J?sm>L?s[5K?sd2H?XI2K?XR5K?smAL
?=.)J?smAN@:<PO?sm>K?XI2K?smAM?smAM?sd8J@:<PO@:<SP?t!JP@:<SQ@:<PN
?XR8M?t!AK?=$uI?sd;K?X[>OAS#FdD0^l"P)=sHKReK!I!KpUEGBQBG&V/,A7TJ%
I;E_ne]Q=hj/?s3D/X</IXmZJWMQr-Za7$G[^s&]\[f8\\@K,Z\[f5]]Xtnn`lZ9A
_8=")^VRb&^VIUu]XkMRUQg@TEG]K)B4bdiB4tsmF+&[iG&M/2BkhBqAn,7X@q9(W
?sm>L@:EYQ?smAN@:<SR?sm>K?sm>L@:<VR?t!JP@:3JN?sm>L@:<SQ@UW\R@:<VR
@:<SQ?sd;L?smDP@:3JM?XR8L?sm>K?XR8L?!grH?sd8I?sm>L?sd8K?X@#E?!grH
?smAN?sm>I?XI/J?smAM@:<PO?sd8J?XR8M@:3JN?smAM?sd8K@:<PO@:<SP?smAN
@:<VS@:<PN?XI2L?sm>L?XI2K?XI/J?t!JRB4u$uI#jGJL4t83J:)TaGB\(FChda8
GBIY6AnG[iD/+-uc,.`Ngo,4+Ao2C$J:jA_Xf8\5Za@-J[^s&]]=PSb]"#;]\[oDb
]Y(to`lQ3@_Sa7-^:q@t^:_1n]tChZVk0$)F_to-AnG[hBkM-nBQSoZI<fgJBkqKt
BObIZA7]7Y?smAM@U`bS?XI5M@:<VT@:3GL?sm>L?smDN?XR8M@UW\S@UW\S@:<SR
@:<SQ@:E\S@:<SR?sm>K?smGP@:3JM?sm>L?sd8J?XR5K?X@&H?X@#E?smAM?sd;L
?XI)E?<prG?XI2K?sd8I?=.&I?smAM@:<PO@:*AL?XR5K?smAM?smAM?sd8K?t!GN
@:<SP?=.)J@U`bT@:EVP?sd;M?sm;J?XI5L?!^iE?t*YXBlA<NL4k56NIlP+H[0aU
F`hV@CMIL-H$X@AAn>IaBkhq!`Q$3Gd\:YjA8,jrKSH4mZE1I?Za@0L[^s&]]"5G`
\[f8^]"5Pf]t;%r_oB[8_8F.-]Y2(o]Xk_g]Y(b]W1oc?F`D//AnG^kAnPagBkhO.
It2c\BPD6qBOtU_AS#@[?smAM@:EYR?XI2L@:E\V@:*DL?XR5K?smAM?smDO@UW_T
@UW\R@:<SR@:<SQ@:<VS@:<SR?smDO@:3JL@:3MP@:3GK?XI/I?XI2K?t!GM?XI2K
?sm>L?XR8M?XR8K?smAN?<poG?smAL?XR;M?=%&M@UWYP?smAM?XR5L@:3JN?smAM
?sd8I@:3JN?t!JP@:<SR@:<SQ@:<SR@:*DM?=.&I?sd;K?<prI?t3tkJVJu7IXd9<
KnFPpJ:;`bCMR[!BkV$hJ:)KL@U`eUA7TD.YILm7RuD]/A7T1[H[VBNXerD.ZEppG
[^`l\]",A^]">Ve]"5Yj^V.Iu^r"%4a2,R-^r!q&]tV1o]=b__Yc=RqJTbmAAn>Od
BP(jgA7fOiEcueSDId9gBP(a]?XRM\@UiqW@UNVO@:<SQ@:<SQ@:3GL?XR8L@:E\R
?XI2K@:3JN?smAL@:<SQ@:<SQ@UW_S@:<SR?sd>N@:3JM@:3PQ@:3GL?sm>J?XI2J
?t!GM?XI2K?sm>L?XR8N?smAL?sd;M?!grH?sm>J?=72L?<puL@UWYP?smAM?sd8K
?smAM@:3JN?sd;K@:3JN?t*SR@:<VR@:<SQ@:<SR?sd8K?=7,I@:3JM?<poG@V^CD
Lk1&(K8>)+I=-EjI<]jRBkhEsARf7\HZO+8A7K+Z@q9+mOdM,aL5(>%A7T:`I".ZT
Y,8M.ZEgmG[CEcZ]=Y\e]=bkl]Xtnk^:h=s^r==8aMu38^qdau]tD(n]tM"bZ)X^s
MLBS]B4bdhAnP^fA7]@`C2\<AEbArpB4bU]?t!PV@:<SR@:<SQ@:<SP@:<SQ@:3GM
?smAL@:<SP?XI2K?sd8K?t!GN@:<VR@UW_S@:E\S@:<SQ?smDO@:3JM?XI2L@:<MN
?XI/I?XI2K?XR8K?sd;L?t!GN?XR8M?sm>L?sd;M?=.&I@:3JM?XR;M?!^oJ@:<SP
?smAM?sd8L?smAM@:3JM?smAK@:<PO?t*SR?t!MQ@:<SQ@:<VR@:*AL?=.)J@:3JN
?!q&KCQP?TKR%rrJ9uEeJUDroG]Rh@C1h-g@Uj%^CMds"@q0"ZA7T1]Df]rDI"[6%
An,@`I=IcUY,Se5Za7!F[C*NT]"5Jb]=kql]Y2"m^:q@u`lcHKcHF;G_nj.%]tV4p
]t:kaYcXk%PDaj1C1_'jAS,OcA7fIdB5)+%GAUr%A7K+[@UW\R?smAM?smAM@:<SP
@:<SP?sd8K?smAM@:<SP?XR8L?sm>L?smAM@UW\R@U`bT@U`bS@:<SQ?t!JP@:3MM
?X@/K@:3GL?XI/H?XI5L?XI/I?XI2L?smAM?smAN?smAM?smAN?=.&I?sm>J?X[AN
?!^lI@:<SP?smAM?sd8L@:3JN@:3JM?sd;J@:<PO@:<SQ?t!MQ@UW\S@:<SQ?sd8K
?=%#J?t!DM?XR8MFL0)UJ:2ffEHZYRJ:2lnFDl#2An5FbB4u$kA86!o@qK=b@q0"Y
AS5UjH%LTrDId9hIY4/]YGeh5['R*FZaR?Q\@K/]]"5Pe]th@s^;.J#aihlUe',qQ
`PK=%]tV7r]tCqaYcb(.S=#:bDeN]oA7T:`AnPdjB4b[dChm]p@U`hZA7K"S?smAM
?smAM?smAM?smAM?sm>L?XR8L@:<VP?XI2L?sd8K?XR8L@UW\R@:<VR@:<SR@:EYR
?t<bW@:3JM?!^rI@:<MN?XI,H?=.)J?XI/I?sm>L?smAM?XR8M?XR8L?XR8M?XR8M
?t!DK?=7/J?!^oJ@:<PO?smAM?XI/K?smAM@:3GL?smAL@:3JN@:<VR?smAN@:<SQ
@:EYR@:*DM?smDO@:<SQ?XR8NGco,_R=01"Fa&:^IslH]E,99%A7T:dBOt^b@UiqZ
A7fFaA7K+[A7]=aE.!1fG%P5qI=e#\YGnk5['I$DZaI6N\%&uZ]"5Ja^;7Ot]tqJ%
`lH3KdEKbS_ns.$]Y2"l^:h(cZ*1@5URmp7G&(]%ARo:^AS,UhAnGO]A7]:_?t!VX
ARf+T?t!JP?smGQ@:3JN?smAM?t!DL?XR8L@UW\Q?XR8M@:3JM?smAM@U`bT@:E\T
@:E\S@:<SQ@q0"Z@:3JM?=%#I?sm>L?XR5J?X@,J?=$uG?XI/J?smAL?smAN?sm>K
?sd;M?t!JP@:3JM?XR8K?!LcH@UW\Q?smAM?XI2L@:<PO@:*DL?sd;J@:<PO?t!JP
?sm>M@:<SR@:<VR@:*DM?=7/L@:<SO?XI8QFcW]8MgKMeEccSNH$XCHD/*g#AnYgi
An>RcA7K.[@q0"ZA7K.[@V'+[BlJ?JG\1MtH[_NSY,J_4Za7$EZa7'J\%&uZ\\#Ga
^VR[u]Y2,!`5fsAbK@rF_8![r]Y(nj^:h1hZEUO9X/DY\JT#+2ARf7_B4b[cA7T4\
@qB.]@:EYTARo:Z@:EYR@:<VR@UW\R@:<SR?sm>L?XR;M@UW\Q?smAN@:3JM?t!GN
@U`eU@U`eT@UW_S@:<SR@q0"Z@prbP?!UfF?smAL?sd8J?=.)J?sd8J?XI/I?XR8L
?smDO?X[>M?smAN?smDO?smAL?!guH>[:]F@:<SP?smAM?XI2L@:3JN?smAL?sd;J
@:<PO@:<SP?=%#I@:<SR@:<SR@:*AL?=7/L@UW\Q?smDVFafRXLk9qmF*2SHDf]o9
CM7I"An>RdAS,Lc@q0"W@UinX@q9(Z@q9%WA8#n)G%kMuFaBLEY,AS.Za7!DZEpmF
\$rlV\\#Ga^;%M!]=bqr`lH$9`l5p5_8!Xr]Y(ni^:q:k['I'FZ)sptNH/T?A7T7a
An>OaA7T4\@UrtZ@:<SQ@V'+_@q9([@:<SQ@:<SQ@:<SR?smAL?smAN@:EYQ?smAN
@:3JM?t!JO@:<SQ@U`bS@:<SQ@:<SR@q0%Z@preQ>[:]E?sm>L?XR5J?X@,J?XR8J
?=$oC?sd8J?X[AO?X[>L?XR8M?t!JP@:<MM?!guH>[1ZG@:<PO?XR8L?XI2L?t!GN
?sm>L?sd8J@:3JN?t!JP?=%#I?t!JP@:<SR?sm>L?=7/L@:<SP?t!SbKn4r>R#ZT5
E,f]7H#dh;CMITuAR]4^AnGUe@qB.Z@U`eU@q0"XART"U@:X%hG%tQ!Ed!Y5YG\\/
Za-pBZEpmB\$riV\@]>`]=u5!^:_7qaMbg/`50=,^V7Cp]Xthh]tM+i[^<KMZ*:C,
Q[!+PA7B(]ARf4Z@UWbX@qK4]@UWYQ@:Nn_A7T4]@prhS@:<SQ@:<VR?sm>K?smDN
@:<SP?sd;M@:3JN?t!JP?t!JQ@UW\Q@U`bT@U`bS@q9(X?sm>K?!guI@:3MP?XI/I
?XR5K?sd8K?sm>L?=.&I?smAL?XR8K?sd2G@:3JN?smAM?XR8L?sd;M@:3JM?smAM
?smDO?smAM?X@)H?XI2K@U`bR?XI)E?XR/F?!grH@:<SS@UWbTCLV-h@W5drE-$]#
X,hsfOHFd$B5DF(BP(plBk_6oBP;$jAS5Xg@q&nU@Uj"]C1q3iAS#Ib@Uiq^C2.?k
DJao\U7e`qY-G:>[^<EHZa7'J[C*EN\@]Sq`4`t$_8sa<_S*Li]=PSa\[f8]^:h1k
\[T)XYHkI8TSI>mA7T:`AS5Xh@qB4^@q/tU@:E\S@U`eV@q0%[A78nU?smAN?smAM
?XR8M@:<VS?XI2J?sd;L?smGP@U`_Q@:3PS@q&kS@:<VS?smAM@q0"W?sd5I?=72M
?t!JP?sm>K?XI2J?XI2J?sm>L?=%#I?sd8J?XI2J?s[2H?smAM?smAM?XI2J?sd;M
?t!GN?smAM?t!JP@:<PO?sd8J?XI2K@U`bR?s[/G?sm>J?!grH@UW_T@UW_UCh@Es
BmY&[P*;2kZ*fjNN/i@'AnPgnC2%?pBOt[aAnGXeAnG[f@q/tV@Us(^B4tjdA7T7_
@prnZAnY^bDJXcWUS"cqYHbC<['I$CZa.!H[^W]R\[oMk_nNq%^Vdt(]t:e`]t:kd
\[oDc]t1ec\$riVZF.$?U5a2)A7K1^An>RfA7T4\@U`hV@U`eT@:E\U@:E_W@q/qU
@:3MP@:3JO?XR5L@:<VS?sd8J?XR8L?smDO@:EVP@:<VS@U`_R@U`bR?smAMA7K+X
?sm>L?sd;L@UNVQ?sd;K?sd;K?XR5K?XI2J?=.&I?sd8I?=.)J?XR5K?smAM?smAL
?XI/J?XR8L?smDN?smAM?t!JP@:3JN?XI/I?=.&I@:<SP?sd8J@:<SO?XI/I@prkX
@q9.]Ci='3M5ItfUR@F#Q`d$@LQ6k&A7T4`Bk_6nARf.W@UinZAS#FbA7K(X@V'(^
An5C]A7T7^ARf4\An5C]D/+9GU7SQkZ*CU?['[0E['d<M\%'#Z]",Ge_S3n(^:q=n
\[o>^]=PM^\@B)\\[f;^\$icT['[->U60Y4@q&tZAS#C_A7]=^@q&nV@UW\R@:<VS
@:E_V@q0%X?smAL?smAM?smAN@:<SQ?sd;K?smAM?smGQ@U`_Q@:<YU@U`_Q@U`bR
?XR8L@q0"Y@:3JN?smDQ@UNVQ?XR5J?XR5J?XI/J?XR8L?smDO?sm>K?!^lG?XR8M
?smAM?smDN?X@)H?sd;M?t!GN?sd8K?t!JP?t!GN?smAL?smDO?t!GN@:*AM@preS
?XI/IARoCbAS,OdG)_ER[?J,5]UP"=N0BQZKT(FuARf4[AS,Lc@q9%W@:E_VA7K+Z
A7K(Y@q0(^@q0"Y@q9.^AnGUdB4PL^Ch\';S=?U_Z*CR=Za7!C[C*EM[^s)]]=PVe
^r+:3^:h+g\%'#]]=YYc]"5J`\$roX[C!BOZa6j8Tose>@:E_XARf7]A7T4]@q/tV
A78qV?t!MR@q/tX@q0%[?sd;L@:3JN?sd;M@UW_S?sd;K?XI2K@:3MP@:EVP?smDP
@:<PN@:3JO?XR8K@q0"Y@preT@:<YU@preR?sm>L?sm>K?XI/J?sm>L?XR8M@:3GK
?<poG?sm>M?sd;L?t!JO?XI2J?smAM?smAM?sm>K?smDO?t!JO?smAM?smDO@:3GL
@:3MOA78nT?XI/JA7fCbBkM=2T$=@Q`j2kg_4?[AIsZNcJW,.pA7T.[@U`eVA7K+[
@UWbUA7K(XARo:[@U`n[@q9(ZA7T7`AnGXeA7]:^C1q[-R[^@ZZ*CF5YHkLA[C*BJ
[^iu[]">Sc^VnF=]Xtba[^WfY]Xtbe]"5Ja\[T&U['[9NZE^L.Sr\AA@U`kZAn,@^
A7]:^@q/tV@UW_T?t!JR@UikV@:E_U?smDO@:<PO@:*DN@:<SR?smAM?smAM?sd>N
@:<PO?smGP@U`_Q?sm>L?smAO@q0"Y@q0"Y@:<YUA78kR?smAN@:3JN?XR8L?sd8K
?XR8L?sd5H?=.&H?sm>L?smAM?smAM?smAM?sd8J?t!GN@:3GM?t!MP@:<PO?sm>L
?XR;N?sm>K?smAM@:<PO?XR5KAS,RgBm,`?^o*9Rcd';N^l=%tH['XOHAR)aA7K+Y
@:<SSA7T7_@q0"Y@q/tWAnGR`@U`n\@q9(\AS,LcAn>ObA7K1_BkMF(OI)rEYH4k.
Y-G:<Za7!F[CEcY]"5J`]u%t5]t:e`[C!ES]=PP_\@B&Y\[JrS[C*EMYH4^sP_a^1
@q&t[AS#@]A7T7^@q0"X@U`eU?t!MS@U`eV@:<VS?XR;P@UWYQ@:3JO@:<SQ?sm>K
?XR5K?smDO@:<PO?XR>O@UWYP?smAM?t!JQ@q0"YA7K+Z@q0"Y@prbQ?smAM@:3JO
?XI2K?XR8L?XR8L?sd2F?XI2J?s[2H?sd;L?smAM?XI/J?smAL?t!GN?sd8K?t!JO
@:<SP?smAL?smDP@:<MM?X@)H@:*AI?!q&JB4kpmF-O>9YHFdfY2@:KT7V`GG&V>9
DL[1PA7K.\@q0%[AS#FaAS#C^@q&kUAS#@\@U`n]ARo=`AnGUbAnGR`A7fCdB4c."
K9E+.YH+_+Xg,+8ZEgjE['mNV\@B)[]Y28#^Upt`[C!?P\[]/X[^EKK[^ENN[C!<I
X/MPNNIlP'An,:\An>Oa@qB4^@q0%Z@UikV@U`eV@U`eU@UW\R?smGSA7B"X@:3JO
@:<SQ?sd8J?XI2K?sd>N@U`_Q?smGQ@UWYP@:3JN?t!JP@q0"Y@q0"Y@q0"Y@q/nS
?smAN?smAM?XR8K?XI/I?XR5K?X@&D?smDM?sd2H?smAM?t!GM?XI2K?smAM?smAL
?sd;K?t!JO@:<PO?t!DL?smDP@:<PO?s[2J?XI)E?!grIB52-uNleo!_nEOFU!LQU
KnY#$G&M,/ATWHCARo7[AS#FaARo:[B4YXaA7K+XAn>F]@UWe[A7fFcB4baeAS#C^
@qB7bB4Z$uI#+PnXf87sWj&b4YctLAZaRBT[^WfX]=GVh^:Le]ZF%$L[^NWPZa-g=
['[3I['R*GU7%+"Jp_ffB4PI]AnPXbA7]@`A7T+X@q9(YAR](X@:<VS@U`bS?t!JQ
@q&qX@:<SQ@UW\R?sd8K?sd8K?smDO@UWYP?XR>O@U`bS@:3JN@:<SQA7K+Y@:<ST
A7K+ZA78nT@q/qS?XI/I@q&eO?smDN?t!JN?smAM?!U`B@:3JK?sm>K?XR5K?XI2K
?XR2J@:3GL?XI2K?t!JO?smAM@UNPL?=7/K?=.&H?XI2J@UNSN?t3bZB5;1/^r3mt
]tC;4WjSIQL4t%tDJEfrAnlX,@U`eT@:3MP?t!JP?t!MR@UikWARf4Z@UW_TA7]:_
ARoCbAnGO_?smALAnZ"!EI*4fPa7`/TVJ9YWiN8,Za7'J\%0&\]=PSa\$`WMZa@*I
[C3WU\?iQIZEgd?Yct*tOGo!IK6r#oBk1[^An>O_AnPaiBP1sjBP(jgA7K+Y@UW_T
@U`eU@:E_VA7fCa@q&hR?t!GO?XR5J?sd8K?sd>N@:<PO@:<SR@U`eT?smAM@:3JO
A7K+X@:<SS@q0"YA7K%VA7K%T?sd;L@q&hR?smDN?t!JO?sd;L?X6uF?t!GK?sm>J
?XI2K?XI2J?XR5J?XR5I?XI/J?t!JP@:3JN@UNSL?=.)J?!grG?=.)I@prbQ@:Eb]
C1q^d^r4U=Zb``AP*:KHIXH6SBP1mgA7TLj@U`_T@:<SQ?t!JO@:<VS@q/tWA7K+Z
@U`eUA7]:_AS#FaAS#@\@:E\SAnYstDfpGQKnY>BNfoQhTqncoYd(L@\%&rX\@K/]
[^<EJZa7!F[^<NO[Bd'AV5C/dV4<m7Mhcn8KS4u-CM%$cAn5F^A7]=aAS,OcBP1sj
An5F_@UW\R@:E\U@UW\TA7T:a@UWYP?smDO?sd;K?sm>L?smDO@:<PO?t!JQ@UW\R
@:<PO?smDOA7K+X@UW\T@q0"Y@q0"W@q/nS?XR8M@q&hR@UW_R?t!JO?smAL?=.&J
@UWYM?sm>K?XR5K?X@,J?XI/I?sm;J?XI2K?X[AO@:<PO@UNPK?!guI?=7,I?XI2J
@prhU@:a(dC35EFf@/<p\$Ds$P(@n%GB@_:B4YUc@q9=g@q/qV@:<SQ@:<SQ@:<VS
@U`eUA7K+Z@UW_TA7T:aAS,OdAn5@\@UWeYBPD:"E-->HG^+O^JV&N.PF/)DYd(I=
[^N]U\@B)[\$`QK['[3J[C!<IZEU:!OcPN\OGejEK7\`3NJWOGCh@*c@qK7^A7T7_
AS#FbAS#IdAn>Rd@U`eT@UWbV@q&kU@q'"^@:3JN?XR;N?sm>K?sd8K?sd>N@:<PO
?smDP@UW_T@:<SP?smAMA7T1Y@:<SS@q0"Y@q0%Z@q/nS?XI5M@q&qU@U`bP?t!JN
?sm>L?XI/J@U`_N?XR2I?=%#I?X@)H?sm>K?sd8J?XI/J?t!JQ@:<PO@UNSL?!guI
?!grF?XI2J@preW@qK@gH)8<qbhM1&]t:23LO4)[D/<luAnGXg@Us4b@UWbU?smDO
@:<SQ@:<PP@:<SQ@q0"Y@U`eTAnP^gAnPahAn,:Z@:Nk\Bk_F$DfKi;EclPLH$F[_
N0'O&Wj&V/['[<P[^WcV[^<BHZEppFZa-m@XehADKn4f)M2R:MJ;&oBP)bTYE+rfl
@q0+_ARo=^A7T7^@qB4_AnPag@U`eU@U`hX@q/tV@Uit]@:3GN?XR8M?smAL?sm>L
?smDO@:EVP?t!MR@UW_T@:<SQ?smAMA7K+X@:<VT@q0"Y@q0"Y@q/nS?t!JR@q&nW
@prbO?smAL?XR8K?XR5K@UW_P?XR5J?XI2J?XI/I?XI/I?XI/I?XI/I?smGP@:<SP
@UNPL?!q&J?!q#H?XI2J@:Wn\AS,Y'UtN]!`mWJo`P8XKKm.EKC1h*hAS5al@Uj(f
BjtO[@:<PP@:3MP@:3MP?t!JP@UiqY@:E\T@qK@cAnGXeAR](W@q97eC2%L$D/O6.
DK'Z?GBeC]M2RO_S#!-fZ*LaD[C3TR[C!6FZEgdAYHY43Um@!lIt)lmIt*30N/s3e
Q'%5bF)5Du@Uj"_ARo@_A7T4]@qB4^AnPah@q&kU@UinX@:E\T@UiqZ@UWYQ?smAM
?XI/I?smAM?sd>N@:<PO?smDO@:<VS@UW\R?smAMA7T1Z@:EYU@:NeW@q9(Z@q&hR
?smJS@q9%YA7K"Q?t!JN?XI/I?XI/J@UW\N?sd8I?XI2J?XI2K?XR5J?XR5J?=.)I
?t!JP@:<SP@:3GK?=.)J?=.&G?XR8K@:Nk\ASQRg`o5IS\&@=Se]FqfJp(pEBP(gc
AS,Rg@q&t`B4>:Z@:<SQ@:<SQ@:<PO?smDO@U`hW@prhU@V'(\ARo=^A78qX@qB=e
D/!`uBPV<rCi468H$k$jL5(VIOI2Z=YctF=ZF.-LZE^X<YctC:XK\b&RuiP]Mi*=C
MMdCRQ'\#0R['"eEGfE!@Us+dAS#C`A7T4]AS,LcB4bdh@q&nU@U`eU@U`bT@UinX
@q0"W@:3GL?sd;L?XR8L?smDO@:<PO?t!GO@:E\T@U`eS?smAMA7T1Z@:<SS@:<YU
@q0%Z@q&kT?t!PU@q0"ZA7JtP@:E\R?smAM?=$uH@:<SN?sd8J?XI/J?X@,I?sm>K
?XI,H?XI2J?t!JP@:<PO@UEJK?!q)K?=.&H?XI2K@:<YWC4Mt_cfXf4Y+`G\e^;O7
Jo,79B4b^cAS5Xg@:E_\B4>=Z@:<SQ@:3MO@:<PP?t!JP@U`hX@q&nU@:WkX@q9([
A7B"Y@q0.aC27HnBPD-mBkqU0IXcp#Mi3RSP*_T.Vld//ZF%!GXf\\+XfSS&Xf84h
RZiqqPED#lR[p1GU84QYS<o4\Ec5Z$@:Nn^ARo=^A7T4]B4tsjB4bag@q/tW@q0"Y
@U`eU@U`hW@Us"Y@UWYP?XR8L?XI2K?smDO@:<PO?smAM?t!JP@U`bR?sd;LA7K+X
@:<SS@:<SS@q0"Z@U`_Q?t!PTA7K+[ARf+R@:<VQ?smAM?=.&I@:<PM?sd8I?XI/I
?X@,I?sm>K?XR5J?X@)I?t!JP@:<SP@:3GK?=.,L?!q&I?XI5K?XdJWL<SDU]AN+[
J"NgE_q<8;I;`h3BP(jd@V'4d@U`h[C1:^`@:<PP@:<PP?smAM?smDO@UWbWA7K(W
@UiqZA7K.YAn#7\A7T4_Bk_<uBkhBo@Uj(kI#!T:P`M#lR$j>0T;JWkZF.*JXf\Y*
X/W+tWhcAYSsl4<VPpMlX/`%oVPg>fSX#.[E,oW$@:Nq`@q0%[A7K.[B4tskAnPXc
A7K(X@UinY@q&nU@q&qX@:a"\@prbR?XR5K?XR8L?smDO@:<PO?smAM?smDO@:3MO
?XR5K~>
%%EndBinary
grestore end % Image Trailer grestore
grestore % EPS grestore
